pub(crate) struct ValidVersions {
    inner: u8,
}

impl ValidVersions {
    const VANILLA: u8 = 1;
    const TBC: u8 = 2;
    const WRATH: u8 = 4;

    pub const fn new(vanilla: bool, tbc: bool, wrath: bool) -> Self {
        let vanilla = if vanilla { Self::VANILLA } else { 0 };
        let tbc = if tbc { Self::TBC } else { 0 };
        let wrath = if wrath { Self::WRATH } else { 0 };

        Self {
            inner: vanilla | tbc | wrath,
        }
    }

    pub const fn vanilla(&self) -> bool {
        self.inner & Self::VANILLA != 0
    }

    pub const fn tbc(&self) -> bool {
        self.inner & Self::TBC != 0
    }

    pub const fn wrath(&self) -> bool {
        self.inner & Self::WRATH != 0
    }
}

pub(crate) struct RawPosition {
    pub map: u32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub orientation: f32,
    pub names: Vec<&'static str>,
    pub valid_versions: ValidVersions,
}

impl RawPosition {
    pub fn new(
        map: u32,
        x: f32,
        y: f32,
        z: f32,
        orientation: f32,
        names: Vec<&'static str>,
        valid_versions: ValidVersions,
    ) -> Self {
        Self {
            map,
            x,
            y,
            z,
            orientation,
            names,
            valid_versions,
        }
    }

    pub const fn no_names(map: u32, x: f32, y: f32, z: f32) -> Self {
        Self {
            map,
            x,
            y,
            z,
            orientation: 0.0,
            names: vec![],
            valid_versions: ValidVersions::new(false, false, false),
        }
    }
}

pub(crate) fn positions() -> Vec<RawPosition> {
    vec![
        RawPosition::new(
            0,
            -8828.8,
            625.6,
            93.9,
            0.7,
            vec!["Stormwind", "SW"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            1493.0,
            -4413.5,
            23.1,
            0.2,
            vec!["Orgrimmar", "Org"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -4926.8,
            -948.1,
            501.6,
            5.4,
            vec!["Ironforge", "IF"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            9951.9,
            2280.3,
            1341.4,
            1.6,
            vec!["Darnassus", "Dar"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            1559.0,
            225.0,
            -43.1,
            0.5,
            vec!["Undercity", "UC"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -9489.7,
            68.1,
            56.0,
            6.1,
            vec!["Goldshire"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -7192.2,
            -3804.7,
            9.8,
            0.0,
            vec!["Gadgetzan"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -8201.8,
            -4622.9,
            8.9,
            5.0,
            vec!["Caverns Of Time"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -7087.1,
            -1275.5,
            -182.8,
            3.5,
            vec!["Fire Plume Ridge"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -6189.1,
            -1107.5,
            -217.7,
            0.6,
            vec!["Marshals Refuge"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -6817.7,
            815.3,
            50.4,
            4.8,
            vec!["Cenarion Hold"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -8183.4,
            1533.6,
            4.2,
            3.1,
            vec!["Ahn'Qiraj", "AQ"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            16226.2,
            16257.0,
            13.2,
            1.7,
            vec!["GM Island"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            451,
            16215.6,
            16112.9,
            69.4,
            2.4,
            vec!["Programmer Isle"],
            ValidVersions::new(true, false, false),
        ),
        RawPosition::new(
            451,
            16246.8,
            -16214.3,
            66.5,
            0.9,
            vec!["Designer Island"],
            ValidVersions::new(true, false, false),
        ),
        RawPosition::new(
            169,
            -366.1,
            3097.9,
            92.3,
            0.0,
            vec!["Emerald Dream"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            13,
            0.0,
            0.0,
            0.0,
            0.0,
            vec!["Testing"],
            ValidVersions::new(true, false, false),
        ),
        RawPosition::new(
            25,
            0.0,
            0.0,
            10.0,
            0.0,
            vec!["Scott Test"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            42,
            0.0,
            0.0,
            0.0,
            0.0,
            vec!["Collins Test"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            36,
            -1689.9,
            800.9,
            10.4,
            4.5,
            vec!["Deadmines Outland"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            29,
            2.0,
            0.0,
            -144.7,
            0.0,
            vec!["Cash Test"],
            ValidVersions::new(true, false, false),
        ),
        RawPosition::new(
            1,
            -10063.5,
            -5667.1,
            -503.4,
            3.1,
            vec!["Tanaris Underwater Goblin Buildings South"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -9643.6,
            -5616.6,
            -503.4,
            5.6,
            vec!["Tanaris Underwater Goblin Buildings North"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            4264.9,
            -2782.7,
            6.0,
            0.5,
            vec!["Quel'Thalas"],
            ValidVersions::new(true, false, false),
        ),
        RawPosition::new(
            0,
            -4844.2,
            -1066.9,
            501.0,
            4.6,
            vec!["Old Ironforge Entrance"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -14407.4,
            420.5,
            22.4,
            1.2,
            vec!["Booty Bay", "BB"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -13228.4,
            228.7,
            33.0,
            1.1,
            vec!["Gurubashi Arena", "Arena"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -12409.3,
            208.2,
            31.6,
            6.3,
            vec!["Grom'gol Base Camp"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -11916.2,
            -1206.5,
            92.3,
            4.7,
            vec!["Zul Gurub", "ZG"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -11813.2,
            1238.1,
            1.1,
            2.8,
            vec!["Yojamba Isle"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -11328.0,
            -203.4,
            75.4,
            0.3,
            vec!["Rebel Camp"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -10556.5,
            -1174.8,
            27.8,
            1.7,
            vec!["Darkshire"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -10761.9,
            310.5,
            37.3,
            0.2,
            vec!["Raven Hill"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -10594.4,
            -435.3,
            84.2,
            6.2,
            vec!["Twilight Grove"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -10516.4,
            1066.4,
            55.1,
            5.2,
            vec!["Sentinell Hill"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -11207.7,
            1673.0,
            24.7,
            1.6,
            vec!["Deadmines", "DM", "VC"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -9472.1,
            -1297.9,
            41.3,
            2.0,
            vec!["Eastvale Logging Camp"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -11123.1,
            -2015.5,
            47.1,
            0.8,
            vec!["Karazhan", "KZ"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -10437.8,
            -3261.4,
            20.2,
            3.3,
            vec!["Stonard"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -10183.2,
            -3993.1,
            -109.2,
            6.0,
            vec!["Sunken Temple", "ST"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -11087.1,
            -3478.7,
            67.1,
            0.5,
            vec!["Nethergarde Keep"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -11865.1,
            -3203.4,
            -22.8,
            3.3,
            vec!["The Dark Portal"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -12078.1,
            -2385.6,
            63.3,
            3.9,
            vec!["The Tainted Scar", "Kazzak"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -9270.1,
            -2188.6,
            64.1,
            4.7,
            vec!["Lakeshire"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -8346.3,
            -2745.6,
            182.8,
            3.5,
            vec!["Morgans Vigil"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -7499.6,
            -1068.4,
            264.5,
            3.6,
            vec!["Blackrock Mountain", "BRM"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -7528.4,
            -1222.5,
            285.7,
            5.3,
            vec!["Blackrock Spire", "BRS", "LBRS", "UBRS"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -7660.1,
            -1220.3,
            287.8,
            2.7,
            vec!["Blackwing Lair", "BWL"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -7515.3,
            -1045.5,
            182.3,
            0.7,
            vec!["Molten Core", "MC"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -7181.1,
            -917.2,
            165.5,
            5.0,
            vec!["Blackrock Depths", "BRD"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -6538.5,
            -1167.6,
            309.3,
            3.8,
            vec!["Thorium Point"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -6693.4,
            -2187.7,
            247.0,
            0.1,
            vec!["Kargath"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -6082.4,
            -2956.2,
            204.9,
            0.1,
            vec!["Uldaman", "Ulda"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -5410.3,
            -2919.5,
            344.1,
            5.9,
            vec!["Thelsamar"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -5631.0,
            -484.0,
            397.0,
            0.1,
            vec!["Kharanos"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -3778.0,
            -788.4,
            8.4,
            2.1,
            vec!["Menethil Harbor"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -1261.2,
            -2506.5,
            21.0,
            5.3,
            vec!["Refuge Point"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -1197.9,
            -2532.7,
            22.4,
            0.0,
            vec!["Arathi Basin", "AB"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -920.3,
            -3498.5,
            70.5,
            3.7,
            vec!["Hammerfall"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -31.9,
            -924.5,
            54.5,
            4.4,
            vec!["Tarren Mill"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -842.7,
            -535.2,
            12.3,
            2.8,
            vec!["Southshore"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            508.8,
            1620.8,
            125.4,
            1.6,
            vec!["The Sepulcher"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -233.8,
            1564.7,
            76.9,
            1.3,
            vec!["Shadowfang Keep", "SFK"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            103.1,
            -187.2,
            127.1,
            1.9,
            vec!["Alterac Valley Alliance"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            534.3,
            -1087.9,
            106.1,
            0.7,
            vec!["Alterac Valley Horde"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            288.1,
            -2006.4,
            194.1,
            4.0,
            vec!["Aerie Peak"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -559.7,
            -4583.3,
            9.8,
            3.8,
            vec!["Revantusk Village"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            958.5,
            -1436.1,
            63.2,
            1.5,
            vec!["Chillwind Camp"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            1264.3,
            -2558.6,
            94.1,
            0.5,
            vec!["Scholomance", "Scholo"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            2282.7,
            -5317.5,
            88.6,
            5.3,
            vec!["Lights Hope Chapel"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            3391.0,
            -3413.6,
            142.3,
            1.5,
            vec!["Stratholme Front", "Strat", "Strat Living"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            3230.8,
            -4039.0,
            108.4,
            5.1,
            vec!["Stratholme Back", "Strat Undead", "Strat UD"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            2902.8,
            -1461.6,
            147.0,
            1.1,
            vec!["Hearthglenn"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            2892.2,
            -810.6,
            160.3,
            0.4,
            vec!["Scarlet Monastary", "SM"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            2237.7,
            289.4,
            35.2,
            6.1,
            vec!["Brill"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            9861.5,
            980.3,
            1307.9,
            3.9,
            vec!["Dolanaar"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            7964.5,
            -2492.7,
            487.8,
            3.2,
            vec!["Nighthaven"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            6415.3,
            485.3,
            8.2,
            6.2,
            vec!["Auberdine"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            3989.7,
            -1293.4,
            251.3,
            6.1,
            vec!["Emerald Sanctuary"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            5097.3,
            -331.2,
            363.3,
            6.2,
            vec!["Bloodvenom Post"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            6149.3,
            -1916.8,
            574.3,
            5.4,
            vec!["Talonbranch Glade"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            6744.6,
            -4659.3,
            725.6,
            3.1,
            vec!["Everlook"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            4946.1,
            -4542.3,
            854.8,
            3.2,
            vec!["Darkwhisper Gorge"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            2756.6,
            -365.3,
            108.8,
            3.8,
            vec!["Astranaar"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            2312.2,
            -2532.0,
            101.2,
            0.1,
            vec!["Splintertree Post"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            3361.5,
            1001.0,
            4.4,
            2.5,
            vec!["Zoram'gar Outpost"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            2731.0,
            -3872.0,
            99.3,
            3.7,
            vec!["Talrendis Point"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            2312.8,
            -6142.7,
            151.2,
            0.8,
            vec!["Azuregos"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            2863.0,
            -7293.0,
            16.6,
            3.3,
            vec!["Bay Of Storms"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            1812.6,
            -4411.7,
            -18.4,
            5.2,
            vec!["Ragefire Chasm", "RFC"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            2673.0,
            1466.9,
            231.7,
            0.3,
            vec!["Stonetalon Peak"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            932.5,
            902.8,
            104.4,
            2.6,
            vec!["Sun Rock Retreat"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -473.7,
            -2615.6,
            105.7,
            5.9,
            vec!["The Crossroads", "Xroads"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -730.2,
            -2217.7,
            17.0,
            2.8,
            vec!["Wailing Caverns", "WC"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            325.1,
            -4713.4,
            13.5,
            4.4,
            vec!["Razor Hill"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -1265.8,
            116.6,
            130.6,
            5.2,
            vec!["Thunder Bluff", "TB"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -2360.5,
            -402.0,
            -7.2,
            0.2,
            vec!["Bloodhoof Village"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            197.1,
            1283.3,
            194.8,
            2.0,
            vec!["Nijels Point"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -1658.7,
            3096.5,
            30.5,
            1.8,
            vec!["Shadowprey Village"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -1460.0,
            2615.1,
            76.6,
            3.2,
            vec!["Maraudon Orange", "Mara"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -1185.9,
            2880.7,
            85.9,
            5.0,
            vec!["Maraudon Purple"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -4417.9,
            3345.7,
            27.8,
            5.9,
            vec!["Feathermoon Stronghold"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -3520.5,
            1085.6,
            161.0,
            4.7,
            vec!["Dire Maul North", "DMN", "Dire Maul"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -3753.7,
            934.3,
            161.0,
            0.0,
            vec!["Dire Maul East", "DME"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -3823.6,
            1249.8,
            160.3,
            3.1,
            vec!["Dire Maul West", "DMW"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -4404.1,
            211.5,
            25.8,
            1.1,
            vec!["Camp Mojache"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -5442.2,
            -2443.9,
            90.0,
            2.8,
            vec!["Freewind Post"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -4466.6,
            -1669.0,
            81.9,
            0.9,
            vec!["Razorfen Kraul", "RFK"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -4656.7,
            -2516.7,
            80.9,
            4.5,
            vec!["Razorfen Downs", "RFD"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -2369.4,
            -1935.9,
            96.3,
            1.9,
            vec!["Camp Taurajo"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -885.0,
            -3763.1,
            14.5,
            2.8,
            vec!["Ratchet"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -3641.4,
            -4432.2,
            14.5,
            5.7,
            vec!["Theramore Isle"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -4733.0,
            -3743.6,
            55.3,
            3.7,
            vec!["Onyxias Lair", "Onyxia", "Ony"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -6183.5,
            -3953.8,
            -58.7,
            3.2,
            vec!["Mirage Raceway"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -6808.5,
            -2890.8,
            8.9,
            6.3,
            vec!["Zul'Farrak", "ZF"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -9623.2,
            -2784.5,
            7.8,
            3.2,
            vec!["Uldum"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -8502.7,
            -4512.2,
            -211.9,
            1.5,
            vec!["Inside Caverns Of Time"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -6927.3,
            -4800.0,
            10.3,
            5.4,
            vec!["Steamwheedle Port"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            369,
            70.2,
            10.3,
            -4.3,
            3.0,
            vec!["Deeprun Tram Ironforge"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            369,
            71.1,
            2491.2,
            -4.3,
            3.1,
            vec!["Deeprun Tram Stormwind"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -129.1,
            835.6,
            63.6,
            0.0,
            vec!["Ambermill"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -5163.3,
            927.2,
            257.2,
            1.4,
            vec!["Gnomeregan", "Gnomer"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -7501.5,
            -2183.1,
            165.9,
            0.0,
            vec!["Flame Crest"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -8771.9,
            840.2,
            90.9,
            0.7,
            vec!["The Stockades", "Stock", "Stocks"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            24.1,
            -1579.8,
            192.7,
            4.5,
            vec!["Ravenholdt Manor"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            3117.1,
            -3723.7,
            136.4,
            5.8,
            vec!["Naxxramas", "Naxx"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            344.4,
            204.8,
            42.9,
            1.9,
            vec!["Dalaran"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            4250.0,
            740.1,
            -25.7,
            1.3,
            vec!["Blackfathom Deeps", "BFD"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -11826.2,
            -4757.0,
            6.6,
            0.3,
            vec!["South Seas Islands"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            8755.1,
            954.7,
            26.6,
            3.3,
            vec!["Darnassus Below"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -8950.0,
            -132.5,
            83.5,
            0.0,
            vec!["Human Start Zone", "Human Start"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -6240.3,
            331.0,
            382.8,
            6.2,
            vec!["Dwarf Start Zone", "Dwarf Start"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -6240.3,
            331.0,
            382.8,
            6.2,
            vec!["Gnome Start Zone", "Gnome Start"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            10311.3,
            832.5,
            1326.4,
            5.7,
            vec!["Night Elf Start Zone", "Night Elf Start"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -618.5,
            -4251.7,
            38.7,
            0.0,
            vec!["Orc Start Zone", "Orc Start"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -618.5,
            -4251.7,
            38.7,
            0.0,
            vec!["Troll Start Zone", "Troll Start"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -2917.6,
            -258.0,
            53.0,
            0.0,
            vec!["Tauren Start Zone", "Tauren Start"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            1676.7,
            1678.3,
            121.7,
            2.7,
            vec!["Undead Start Zone", "Undead Start"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            530,
            10349.6,
            -6357.29,
            33.4026,
            5.31605,
            vec!["Blood Elf Start Zone", "Blood Elf Start"],
            ValidVersions::new(false, true, true),
        ),
        RawPosition::new(
            530,
            -3961.64,
            -13931.2,
            100.615,
            2.08364,
            vec!["Draenei Start Zone", "Draenei Start"],
            ValidVersions::new(false, true, true),
        ),
        RawPosition::new(
            37,
            126.0,
            125.4,
            232.5,
            4.7,
            vec!["Azshara Crater"],
            ValidVersions::new(true, false, false),
        ),
        RawPosition::new(
            44,
            45.1,
            -0.5,
            15.2,
            0.0,
            vec!["Old Scarlet Monastery"],
            ValidVersions::new(true, false, false),
        ),
        RawPosition::new(
            1,
            7434.3,
            -1559.8,
            187.4,
            2.7,
            vec!["Dancing Troll Village"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            269,
            2394.2,
            1195.9,
            68.2,
            4.1,
            vec!["Old Hillsbrad"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            4617.0,
            -3853.4,
            944.1,
            1.1,
            vec!["Hyjal Start"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            4617.0,
            -3853.4,
            944.1,
            1.1,
            vec!["Hyjal"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            5380.2,
            -3370.0,
            1655.6,
            5.0,
            vec!["Hyjal End"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            5475.9,
            -3728.9,
            1593.4,
            6.0,
            vec!["Hyjal Construction"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            4817.0,
            -1742.0,
            1158.3,
            5.5,
            vec!["Hyjal Portal Outside"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            4858.0,
            -1840.0,
            1143.6,
            4.9,
            vec!["Hyjal Portal Inside"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -10736.9,
            2472.6,
            6.4,
            4.7,
            vec!["Silithus Farm"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            -399.5,
            -2184.8,
            157.7,
            0.3,
            vec!["Shrine Of The Fallen"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            1951.5,
            1530.5,
            247.3,
            0.6,
            vec!["Stonetalon Logging Camp"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            9725.3,
            -21.4,
            18.8,
            0.0,
            vec!["Teldrassil Furbolg Camp"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            520.4,
            -237.5,
            582.3,
            5.3,
            vec!["Stonetalon Help Mountain"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -3853.4,
            -3463.6,
            582.7,
            4.8,
            vec!["Wetlands Help Mountain"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -4796.2,
            -1665.4,
            504.2,
            6.1,
            vec!["Ironforge Airport"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -3981.3,
            -1279.6,
            158.2,
            3.6,
            vec!["Wetlands Farm"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -5308.2,
            -2510.8,
            485.1,
            3.6,
            vec!["Ortell's Hideout"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -12878.0,
            -1411.5,
            120.1,
            0.5,
            vec!["Stranglethorn Secret Cave"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -11073.0,
            -1956.0,
            38.8,
            0.0,
            vec!["Karazhan Smiley"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -8324.0,
            -339.0,
            145.6,
            0.0,
            vec!["Stormwind Falls"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -11084.0,
            -1801.0,
            52.7,
            1.8,
            vec!["Well Of The Forgotten"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -1832.8,
            -4163.3,
            9.9,
            5.8,
            vec!["Arathi Farm"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -6376.3,
            1259.4,
            7.2,
            1.2,
            vec!["Newmann's Landing"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            1698.6,
            239.5,
            -40.7,
            0.0,
            vec!["Undercity Top Tier"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -8521.3,
            599.5,
            101.4,
            0.0,
            vec!["Cut Throat Alley"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -6174.2,
            -772.8,
            420.7,
            6.2,
            vec!["Dun Morogh Plane Camp"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -4601.6,
            -817.8,
            639.3,
            3.9,
            vec!["Dun Morogh Troll Cave"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -5938.4,
            451.6,
            508.3,
            1.9,
            vec!["Forgotten Gnome Camp"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -822.2,
            1555.0,
            22.6,
            6.0,
            vec!["The Greymane Wall"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -5605.4,
            731.8,
            486.0,
            1.5,
            vec!["Isolated Dun Morogh"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            0,
            -7347.0,
            -642.0,
            294.6,
            5.9,
            vec!["Blackchar Cave"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            1,
            16227.0,
            16403.0,
            -64.4,
            0.0,
            vec!["GM Island Room"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            169,
            -2128.1,
            -1005.9,
            132.2,
            0.0,
            vec!["The Verdant Fields"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            169,
            2738.7,
            -3272.1,
            101.1,
            1.2,
            vec!["Emerald Forest"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            169,
            2838.3,
            2996.0,
            27.7,
            1.7,
            vec!["Emerald Statue"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            269,
            -1997.8,
            6572.5,
            -154.9,
            6.0,
            vec!["The Black Morass Start"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            269,
            -1646.0,
            7117.7,
            25.5,
            2.9,
            vec!["The Black Morass Swamp"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            269,
            -2063.8,
            7122.7,
            30.3,
            3.1,
            vec!["The Black Morass Dark Portal"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            35,
            -1.9,
            52.9,
            -27.6,
            1.5,
            vec!["Stormwind Vault"],
            ValidVersions::new(true, true, true),
        ),
        RawPosition::new(
            369,
            3.3,
            1382.3,
            -100.3,
            6.3,
            vec!["Deeprun Tram Aquarium"],
            ValidVersions::new(true, true, true),
        ),
    ]
}
