use crate::rust_printer::{ByteType, MemberType, UfType, UpdateMaskType};

pub(crate) const FIELDS: &[MemberType] = &[
    MemberType::new(UpdateMaskType::Object, "GUID", 0x0, 2, UfType::Guid),
    MemberType::new(UpdateMaskType::Object, "ENTRY", 0x3, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Object, "SCALE_X", 0x4, 1, UfType::Float),
    MemberType::new(UpdateMaskType::Item, "OWNER", 0x6, 2, UfType::Guid),
    MemberType::new(UpdateMaskType::Item, "CONTAINED", 0x8, 2, UfType::Guid),
    MemberType::new(UpdateMaskType::Item, "CREATOR", 0xA, 2, UfType::Guid),
    MemberType::new(UpdateMaskType::Item, "GIFTCREATOR", 0xC, 2, UfType::Guid),
    MemberType::new(UpdateMaskType::Item, "STACK_COUNT", 0xE, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Item, "DURATION", 0xF, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Item, "SPELL_CHARGES", 0x10, 5, UfType::Int),
    MemberType::new(UpdateMaskType::Item, "FLAGS", 0x15, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Item, "ENCHANTMENT", 0x16, 21, UfType::Int),
    MemberType::new(UpdateMaskType::Item, "PROPERTY_SEED", 0x2B, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Item,
        "RANDOM_PROPERTIES_ID",
        0x2C,
        1,
        UfType::Int,
    ),
    MemberType::new(UpdateMaskType::Item, "ITEM_TEXT_ID", 0x2D, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Item, "DURABILITY", 0x2E, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Item, "MAXDURABILITY", 0x2F, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Container, "NUM_SLOTS", 0x30, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Container, "SLOT_1", 0x32, 72, UfType::Guid),
    MemberType::new(UpdateMaskType::Unit, "CHARM", 0x6, 2, UfType::Guid),
    MemberType::new(UpdateMaskType::Unit, "SUMMON", 0x8, 2, UfType::Guid),
    MemberType::new(UpdateMaskType::Unit, "CHARMEDBY", 0xA, 2, UfType::Guid),
    MemberType::new(UpdateMaskType::Unit, "SUMMONEDBY", 0xC, 2, UfType::Guid),
    MemberType::new(UpdateMaskType::Unit, "CREATEDBY", 0xE, 2, UfType::Guid),
    MemberType::new(UpdateMaskType::Unit, "TARGET", 0x10, 2, UfType::Guid),
    MemberType::new(UpdateMaskType::Unit, "PERSUADED", 0x12, 2, UfType::Guid),
    MemberType::new(
        UpdateMaskType::Unit,
        "CHANNEL_OBJECT",
        0x14,
        2,
        UfType::Guid,
    ),
    MemberType::new(UpdateMaskType::Unit, "HEALTH", 0x16, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "POWER1", 0x17, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "POWER2", 0x18, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "POWER3", 0x19, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "POWER4", 0x1A, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "POWER5", 0x1B, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "MAXHEALTH", 0x1C, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "MAXPOWER1", 0x1D, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "MAXPOWER2", 0x1E, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "MAXPOWER3", 0x1F, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "MAXPOWER4", 0x20, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "MAXPOWER5", 0x21, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "LEVEL", 0x22, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Unit,
        "FACTIONTEMPLATE",
        0x23,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "BYTES_0",
        0x24,
        1,
        UfType::BytesWith(
            ByteType::new("race", "Race"),
            ByteType::new("class", "Class"),
            ByteType::new("gender", "Gender"),
            ByteType::new("power", "Power"),
        ),
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "VIRTUAL_ITEM_SLOT_DISPLAY",
        0x25,
        3,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "VIRTUAL_ITEM_INFO",
        0x28,
        6,
        UfType::Bytes,
    ),
    MemberType::new(UpdateMaskType::Unit, "FLAGS", 0x2E, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "AURA", 0x2F, 48, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "AURAFLAGS", 0x5F, 6, UfType::Bytes),
    MemberType::new(UpdateMaskType::Unit, "AURALEVELS", 0x65, 12, UfType::Bytes),
    MemberType::new(
        UpdateMaskType::Unit,
        "AURAAPPLICATIONS",
        0x71,
        12,
        UfType::Bytes,
    ),
    MemberType::new(UpdateMaskType::Unit, "AURASTATE", 0x7D, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "BASEATTACKTIME", 0x7E, 2, UfType::Int),
    MemberType::new(
        UpdateMaskType::Unit,
        "RANGEDATTACKTIME",
        0x80,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "BOUNDINGRADIUS",
        0x81,
        1,
        UfType::Float,
    ),
    MemberType::new(UpdateMaskType::Unit, "COMBATREACH", 0x82, 1, UfType::Float),
    MemberType::new(UpdateMaskType::Unit, "DISPLAYID", 0x83, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Unit,
        "NATIVEDISPLAYID",
        0x84,
        1,
        UfType::Int,
    ),
    MemberType::new(UpdateMaskType::Unit, "MOUNTDISPLAYID", 0x85, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "MINDAMAGE", 0x86, 1, UfType::Float),
    MemberType::new(UpdateMaskType::Unit, "MAXDAMAGE", 0x87, 1, UfType::Float),
    MemberType::new(
        UpdateMaskType::Unit,
        "MINOFFHANDDAMAGE",
        0x88,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "MAXOFFHANDDAMAGE",
        0x89,
        1,
        UfType::Float,
    ),
    MemberType::new(UpdateMaskType::Unit, "BYTES_1", 0x8A, 1, UfType::Bytes),
    MemberType::new(UpdateMaskType::Unit, "PETNUMBER", 0x8B, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Unit,
        "PET_NAME_TIMESTAMP",
        0x8C,
        1,
        UfType::Int,
    ),
    MemberType::new(UpdateMaskType::Unit, "PETEXPERIENCE", 0x8D, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Unit,
        "PETNEXTLEVELEXP",
        0x8E,
        1,
        UfType::Int,
    ),
    MemberType::new(UpdateMaskType::Unit, "DYNAMIC_FLAGS", 0x8F, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "CHANNEL_SPELL", 0x90, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Unit,
        "MOD_CAST_SPEED",
        0x91,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "CREATED_BY_SPELL",
        0x92,
        1,
        UfType::Int,
    ),
    MemberType::new(UpdateMaskType::Unit, "NPC_FLAGS", 0x93, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "NPC_EMOTESTATE", 0x94, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Unit,
        "TRAINING_POINTS",
        0x95,
        1,
        UfType::TwoShort,
    ),
    MemberType::new(UpdateMaskType::Unit, "STRENGTH", 0x96, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "AGILITY", 0x97, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "STAMINA", 0x98, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "INTELLECT", 0x99, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "SPIRIT", 0x9A, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Unit,
        "NORMAL_RESISTANCE",
        0x9B,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "HOLY_RESISTANCE",
        0x9C,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "FIRE_RESISTANCE",
        0x9D,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "NATURE_RESISTANCE",
        0x9E,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "FROST_RESISTANCE",
        0x9F,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "SHADOW_RESISTANCE",
        0xA0,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "ARCANE_RESISTANCE",
        0xA1,
        1,
        UfType::Int,
    ),
    MemberType::new(UpdateMaskType::Unit, "BASE_MANA", 0xA2, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Unit, "BASE_HEALTH", 0xA3, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Unit,
        "BYTES_2",
        0xA4,
        1,
        UfType::BytesWith(
            ByteType::byte("facial_hair"),
            ByteType::byte("unknown"),
            ByteType::byte("bank_bag_slots"),
            ByteType::byte("rested_state"),
        ),
    ),
    MemberType::new(UpdateMaskType::Unit, "ATTACK_POWER", 0xA5, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Unit,
        "ATTACK_POWER_MODS",
        0xA6,
        1,
        UfType::TwoShort,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "ATTACK_POWER_MULTIPLIER",
        0xA7,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "RANGED_ATTACK_POWER",
        0xA8,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "RANGED_ATTACK_POWER_MODS",
        0xA9,
        1,
        UfType::TwoShort,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "RANGED_ATTACK_POWER_MULTIPLIER",
        0xAA,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "MINRANGEDDAMAGE",
        0xAB,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "MAXRANGEDDAMAGE",
        0xAC,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "POWER_COST_MODIFIER",
        0xAD,
        7,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Unit,
        "POWER_COST_MULTIPLIER",
        0xB4,
        7,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "DUEL_ARBITER",
        0xBC,
        2,
        UfType::Guid,
    ),
    MemberType::new(UpdateMaskType::Player, "FLAGS", 0xBE, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Player, "GUILDID", 0xBF, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Player, "GUILDRANK", 0xC0, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Player, "FEATURES", 0xC1, 1, UfType::Bytes),
    MemberType::new(UpdateMaskType::Player, "BYTES_2", 0xC2, 1, UfType::Bytes),
    MemberType::new(UpdateMaskType::Player, "BYTES_3", 0xC3, 1, UfType::Bytes),
    MemberType::new(UpdateMaskType::Player, "DUEL_TEAM", 0xC4, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Player,
        "GUILD_TIMESTAMP",
        0xC5,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_1_1",
        0xC6,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_1_2",
        0xC7,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_2_1",
        0xC9,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_2_2",
        0xCA,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_3_1",
        0xCC,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_3_2",
        0xCD,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_4_1",
        0xCF,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_4_2",
        0xD0,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_5_1",
        0xD2,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_5_2",
        0xD3,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_6_1",
        0xD5,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_6_2",
        0xD6,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_7_1",
        0xD8,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_7_2",
        0xD9,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_8_1",
        0xDB,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_8_2",
        0xDC,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_9_1",
        0xDE,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_9_2",
        0xDF,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_10_1",
        0xE1,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_10_2",
        0xE2,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_11_1",
        0xE4,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_11_2",
        0xE5,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_12_1",
        0xE7,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_12_2",
        0xE8,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_13_1",
        0xEA,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_13_2",
        0xEB,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_14_1",
        0xED,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_14_2",
        0xEE,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_15_1",
        0xF0,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_15_2",
        0xF1,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_16_1",
        0xF3,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_16_2",
        0xF4,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_17_1",
        0xF6,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_17_2",
        0xF7,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_18_1",
        0xF9,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_18_2",
        0xFA,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_19_1",
        0xFC,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_19_2",
        0xFD,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_20_1",
        0xFF,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "QUEST_LOG_20_2",
        0x100,
        2,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "VISIBLE_ITEM",
        0x102,
        228,
        UfType::ArrayOfStruct {
            name: "VisibleItem",
            variable_name: "visible_item",
            import_location: "crate::vanilla",
            size: 12,
        },
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_INV",
        0x1E6,
        226,
        UfType::GuidEnumLookupArray {
            name: "ItemSlot",
            variable_name: "item_slot",
            import_location: "crate::vanilla",
        },
    ),
    MemberType::new(UpdateMaskType::Player, "FARSIGHT", 0x2C8, 2, UfType::Guid),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_COMBO_TARGET",
        0x2CA,
        2,
        UfType::Guid,
    ),
    MemberType::new(UpdateMaskType::Player, "XP", 0x2CC, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Player,
        "NEXT_LEVEL_XP",
        0x2CD,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "SKILL_INFO",
        0x2CE,
        384,
        UfType::ArrayOfStruct {
            name: "SkillInfo",
            variable_name: "skill_info",
            import_location: "crate::vanilla",
            size: 3,
        },
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "CHARACTER_POINTS1",
        0x44E,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "CHARACTER_POINTS2",
        0x44F,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "TRACK_CREATURES",
        0x450,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "TRACK_RESOURCES",
        0x451,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "BLOCK_PERCENTAGE",
        0x452,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "DODGE_PERCENTAGE",
        0x453,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "PARRY_PERCENTAGE",
        0x454,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "CRIT_PERCENTAGE",
        0x455,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "RANGED_CRIT_PERCENTAGE",
        0x456,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "EXPLORED_ZONES_1",
        0x457,
        64,
        UfType::Bytes,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "REST_STATE_EXPERIENCE",
        0x497,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_COINAGE",
        0x498,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_POSSTAT0",
        0x499,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_POSSTAT1",
        0x49A,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_POSSTAT2",
        0x49B,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_POSSTAT3",
        0x49C,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_POSSTAT4",
        0x49D,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_NEGSTAT0",
        0x49E,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_NEGSTAT1",
        0x49F,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_NEGSTAT2",
        0x4A0,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_NEGSTAT3",
        0x4A1,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_NEGSTAT4",
        0x4A2,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_RESISTANCEBUFFMODSPOSITIVE",
        0x4A3,
        7,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_RESISTANCEBUFFMODSNEGATIVE",
        0x4AA,
        7,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_MOD_DAMAGE_DONE_POS",
        0x4B1,
        7,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_MOD_DAMAGE_DONE_NEG",
        0x4B8,
        7,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_MOD_DAMAGE_DONE_PCT",
        0x4BF,
        7,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_BYTES",
        0x4C6,
        1,
        UfType::Bytes,
    ),
    MemberType::new(UpdateMaskType::Player, "AMMO_ID", 0x4C7, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Player,
        "SELF_RES_SPELL",
        0x4C8,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_PVP_MEDALS",
        0x4C9,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_BUYBACK_PRICE_1",
        0x4CA,
        12,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_BUYBACK_TIMESTAMP_1",
        0x4D6,
        12,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_SESSION_KILLS",
        0x4E2,
        1,
        UfType::TwoShort,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_YESTERDAY_KILLS",
        0x4E3,
        1,
        UfType::TwoShort,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_LAST_WEEK_KILLS",
        0x4E4,
        1,
        UfType::TwoShort,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_THIS_WEEK_KILLS",
        0x4E5,
        1,
        UfType::TwoShort,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_THIS_WEEK_CONTRIBUTION",
        0x4E6,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_LIFETIME_HONORBALE_KILLS",
        0x4E7,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_LIFETIME_DISHONORBALE_KILLS",
        0x4E8,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_YESTERDAY_CONTRIBUTION",
        0x4E9,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_LAST_WEEK_CONTRIBUTION",
        0x4EA,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_LAST_WEEK_RANK",
        0x4EB,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_BYTES2",
        0x4EC,
        1,
        UfType::Bytes,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_WATCHED_FACTION_INDEX",
        0x4ED,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::Player,
        "FIELD_COMBAT_RATING_1",
        0x4EE,
        20,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::GameObject,
        "CREATED_BY",
        0x6,
        2,
        UfType::Guid,
    ),
    MemberType::new(UpdateMaskType::GameObject, "DISPLAYID", 0x8, 1, UfType::Int),
    MemberType::new(UpdateMaskType::GameObject, "FLAGS", 0x9, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::GameObject,
        "ROTATION",
        0xA,
        4,
        UfType::Float,
    ),
    MemberType::new(UpdateMaskType::GameObject, "STATE", 0xE, 1, UfType::Int),
    MemberType::new(UpdateMaskType::GameObject, "POS_X", 0xF, 1, UfType::Float),
    MemberType::new(UpdateMaskType::GameObject, "POS_Y", 0x10, 1, UfType::Float),
    MemberType::new(UpdateMaskType::GameObject, "POS_Z", 0x11, 1, UfType::Float),
    MemberType::new(UpdateMaskType::GameObject, "FACING", 0x12, 1, UfType::Float),
    MemberType::new(
        UpdateMaskType::GameObject,
        "DYN_FLAGS",
        0x13,
        1,
        UfType::Int,
    ),
    MemberType::new(UpdateMaskType::GameObject, "FACTION", 0x14, 1, UfType::Int),
    MemberType::new(UpdateMaskType::GameObject, "TYPE_ID", 0x15, 1, UfType::Int),
    MemberType::new(UpdateMaskType::GameObject, "LEVEL", 0x16, 1, UfType::Int),
    MemberType::new(UpdateMaskType::GameObject, "ARTKIT", 0x17, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::GameObject,
        "ANIMPROGRESS",
        0x18,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::DynamicObject,
        "CASTER",
        0x6,
        2,
        UfType::Guid,
    ),
    MemberType::new(
        UpdateMaskType::DynamicObject,
        "BYTES",
        0x8,
        1,
        UfType::Bytes,
    ),
    MemberType::new(
        UpdateMaskType::DynamicObject,
        "SPELLID",
        0x9,
        1,
        UfType::Int,
    ),
    MemberType::new(
        UpdateMaskType::DynamicObject,
        "RADIUS",
        0xA,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::DynamicObject,
        "POS_X",
        0xB,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::DynamicObject,
        "POS_Y",
        0xC,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::DynamicObject,
        "POS_Z",
        0xD,
        1,
        UfType::Float,
    ),
    MemberType::new(
        UpdateMaskType::DynamicObject,
        "FACING",
        0xE,
        1,
        UfType::Float,
    ),
    MemberType::new(UpdateMaskType::Corpse, "OWNER", 0x6, 2, UfType::Guid),
    MemberType::new(UpdateMaskType::Corpse, "FACING", 0x8, 1, UfType::Float),
    MemberType::new(UpdateMaskType::Corpse, "POS_X", 0x9, 1, UfType::Float),
    MemberType::new(UpdateMaskType::Corpse, "POS_Y", 0xA, 1, UfType::Float),
    MemberType::new(UpdateMaskType::Corpse, "POS_Z", 0xB, 1, UfType::Float),
    MemberType::new(UpdateMaskType::Corpse, "DISPLAY_ID", 0xC, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Corpse, "ITEM", 0xD, 19, UfType::Int),
    MemberType::new(UpdateMaskType::Corpse, "BYTES_1", 0x20, 1, UfType::Bytes),
    MemberType::new(UpdateMaskType::Corpse, "BYTES_2", 0x21, 1, UfType::Bytes),
    MemberType::new(UpdateMaskType::Corpse, "GUILD", 0x22, 1, UfType::Int),
    MemberType::new(UpdateMaskType::Corpse, "FLAGS", 0x23, 1, UfType::Int),
    MemberType::new(
        UpdateMaskType::Corpse,
        "DYNAMIC_FLAGS",
        0x24,
        1,
        UfType::Int,
    ),
];
