use crate::extended::wrath::trigger::AreaTrigger;
use crate::wrath::Map;
use crate::wrath::position::Position;
use crate::wrath::trigger::Trigger;

pub(crate) const TRIGGERS: &[(u32, (AreaTrigger, Trigger))] = &[
// AUTOGENERATED_START
(45, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, 2924.4, -798.4, 161.6, 0.0), radius: 8.0 }, 
    Trigger::Teleport { location: Position::new(Map::ScarletMonastery, 1687.3, 1050.1, 18.7, 1.6),required_level: 20,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(71, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -10645.9, 1179.1, 48.2, 0.0), radius: 27.0 }, 
    Trigger::Inn
)),
(78, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -11208.5, 1685.3, 25.8, 0.0), radius: 7.0 }, 
    Trigger::Teleport { location: Position::new(Map::Deadmines, -14.6, -385.5, 62.5, 1.6),required_level: 10,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(98, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -11634.8, -54.1, 13.4, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(101, (
    AreaTrigger::Square { position: Position::new(Map::EasternKingdoms, -8761.8, 848.6, 87.8, 0.0), length: 5.0, width: 9.7, height: 7.4, yaw: 0.7 },
    Trigger::Teleport { location: Position::new(Map::StormwindStockade, 49.0, 0.5, -16.4, 0.0),required_level: 15,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(107, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -8667.6, 623.6, 85.4, 0.0), radius: 7.0 }, 
    Trigger::Teleport { location: Position::new(Map::Stormwindprison, -0.9, 40.6, -24.2, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(109, (
    AreaTrigger::Circle { position: Position::new(Map::Stormwindprison, -0.9, 16.4, -14.2, 0.0), radius: 7.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -8653.5, 606.2, 91.2, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(119, (
    AreaTrigger::Circle { position: Position::new(Map::Deadmines, -14.4, -393.4, 64.6, 0.0), radius: 6.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -11208.7, 1675.9, 24.6, 4.7),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(121, (
    AreaTrigger::Circle { position: Position::new(Map::Deadmines, -110.8, -1009.2, 34.8, 0.0), radius: 7.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -11339.9, 1572.4, 94.4, 1.6),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(145, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -229.5, 1576.3, 78.9, 0.0), radius: 7.0 }, 
    Trigger::Teleport { location: Position::new(Map::ShadowfangKeep, -228.2, 2111.4, 76.9, 1.2),required_level: 10,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(178, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, 683.8, -912.1, 174.5, 0.0), radius: 5.0 }, 
    Trigger::Inn
)),
(194, (
    AreaTrigger::Circle { position: Position::new(Map::ShadowfangKeep, -231.0, 2105.1, 79.8, 0.0), radius: 5.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -233.0, 1567.5, 76.9, 4.3),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(226, (
    AreaTrigger::Circle { position: Position::new(Map::WailingCaverns, -172.2, 139.0, -66.6, 0.0), radius: 12.0 }, 
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -740.1, -2214.2, 16.1, 5.7),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(228, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -753.6, -2212.8, 21.5, 0.0), radius: 13.0 }, 
    Trigger::Teleport { location: Position::new(Map::WailingCaverns, -163.5, 132.9, -73.7, 5.8),required_level: 10,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(242, (
    AreaTrigger::Circle { position: Position::new(Map::RazorfenKraul, 1936.4, 1534.5, 86.9, 0.0), radius: 8.0 }, 
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -4463.3, -1664.3, 82.2, 3.9),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(244, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -4456.7, -1656.0, 86.1, 0.0), radius: 8.0 }, 
    Trigger::Teleport { location: Position::new(Map::RazorfenKraul, 1942.3, 1544.2, 81.8, 1.3),required_level: 17,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(257, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, 4252.4, 757.0, -23.1, 0.0), radius: 12.0 }, 
    Trigger::Teleport { location: Position::new(Map::BlackfathomDeeps, -150.2, 106.6, -39.8, 4.5),required_level: 19,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(259, (
    AreaTrigger::Circle { position: Position::new(Map::BlackfathomDeeps, -148.6, 121.1, -33.4, 0.0), radius: 12.0 }, 
    Trigger::Teleport { location: Position::new(Map::Kalimdor, 4247.7, 745.9, -24.5, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(286, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -6053.7, -2954.6, 213.7, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::Uldaman, -228.9, 46.1, -46.0, 1.6),required_level: 30,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(288, (
    AreaTrigger::Circle { position: Position::new(Map::Uldaman, -228.2, 34.2, -39.2, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -6066.2, -2954.6, 209.8, 3.1),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(322, (
    AreaTrigger::Circle { position: Position::new(Map::Gnomeregan, -312.2, -4.6, -148.7, 0.0), radius: 14.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -5163.3, 927.6, 257.2, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(324, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -5161.3, 939.6, 258.3, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::Gnomeregan, -329.1, -3.2, -152.9, 3.0),required_level: 20,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(442, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -4666.5, -2536.8, 87.0, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::RazorfenDowns, 2592.6, 1107.5, 51.3, 4.7),required_level: 25,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(444, (
    AreaTrigger::Circle { position: Position::new(Map::RazorfenDowns, 2593.9, 1124.6, 56.2, 0.0), radius: 11.0 }, 
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -4658.1, -2526.4, 83.0, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(446, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -10162.7, -3998.6, -108.0, 0.0), radius: 11.0 }, 
    Trigger::Teleport { location: Position::new(Map::SunkenTemple, -315.9, 100.2, -131.8, 3.1),required_level: 35,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(448, (
    AreaTrigger::Circle { position: Position::new(Map::SunkenTemple, -300.0, 99.0, -127.0, 0.0), radius: 13.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -10176.6, -3995.4, -112.2, 3.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(503, (
    AreaTrigger::Circle { position: Position::new(Map::StormwindStockade, 39.4, 0.8, -12.8, 0.0), radius: 8.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -8766.1, 845.5, 88.0, 3.8),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(523, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -4858.3, 785.0, 241.1, 0.0), radius: 12.0 }, 
    Trigger::Teleport { location: Position::new(Map::Gnomeregan, -736.5, 2.7, -250.0, 3.1),required_level: 20,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(525, (
    AreaTrigger::Circle { position: Position::new(Map::Gnomeregan, -717.9, 1.4, -241.3, 0.0), radius: 12.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -4858.3, 756.4, 244.9, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(527, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, 9947.5, 2630.0, 1318.6, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::Kalimdor, 8786.4, 967.4, 30.2, 3.4),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(542, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, 8799.4, 969.8, 30.2, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::Kalimdor, 9945.1, 2616.9, 1316.5, 4.6),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(562, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -9465.6, 16.8, 65.9, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(602, (
    AreaTrigger::Circle { position: Position::new(Map::ScarletMonastery, 1687.6, 1040.1, 21.0, 0.0), radius: 8.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, 2915.3, -801.6, 160.3, 3.5),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(604, (
    AreaTrigger::Circle { position: Position::new(Map::ScarletMonastery, 853.7, 1308.1, 19.7, 0.0), radius: 8.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, 2915.1, -823.6, 160.3, 3.5),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(606, (
    AreaTrigger::Circle { position: Position::new(Map::ScarletMonastery, 1608.7, -309.0, 20.8, 0.0), radius: 8.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, 2886.0, -835.8, 160.3, 0.3),required_level: 20,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(608, (
    AreaTrigger::Circle { position: Position::new(Map::ScarletMonastery, 253.6, -196.8, 21.0, 0.0), radius: 8.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, 2869.3, -820.8, 160.3, 0.3),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(610, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, 2925.2, -820.5, 161.6, 0.0), radius: 8.0 }, 
    Trigger::Teleport { location: Position::new(Map::ScarletMonastery, 853.2, 1319.2, 18.7, 1.6),required_level: 20,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(612, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, 2878.0, -839.3, 163.0, 0.0), radius: 6.0 }, 
    Trigger::Teleport { location: Position::new(Map::ScarletMonastery, 1608.1, -318.9, 18.7, 4.7),required_level: 20,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(614, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, 2859.7, -824.9, 162.1, 0.0), radius: 8.0 }, 
    Trigger::Teleport { location: Position::new(Map::ScarletMonastery, 253.7, -206.6, 18.7, 4.7),required_level: 20,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(682, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -9219.4, -2149.9, 70.6, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(702, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -9023.3, 892.4, 33.5, 0.0), radius: 7.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -9015.8, 874.6, 148.6, 5.3),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(704, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -9020.1, 880.5, 151.6, 0.0), radius: 7.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -9017.4, 886.3, 29.6, 5.4),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(707, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -10517.0, -1158.4, 39.1, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(708, (
    AreaTrigger::Square { position: Position::new(Map::EasternKingdoms, -854.5, -576.3, 18.5, 0.0), length: 56.2, width: 27.5, height: 28.5, yaw: 4.7 },
    Trigger::Inn
)),
(709, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -3615.5, -4467.3, 24.3, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(710, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -5601.5, -530.7, 395.5, 0.0), radius: 35.0 }, 
    Trigger::Inn
)),
(712, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -5390.2, -2953.9, 322.0, 0.0), radius: 36.0 }, 
    Trigger::Inn
)),
(713, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -3823.1, -834.5, 18.3, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(715, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, 9809.0, 959.2, 1315.3, 0.0), radius: 32.0 }, 
    Trigger::Inn
)),
(716, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, 6410.0, 527.0, 14.1, 0.0), radius: 32.0 }, 
    Trigger::Inn
)),
(717, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, 2756.6, -423.1, 119.4, 0.0), radius: 32.0 }, 
    Trigger::Inn
)),
(719, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, 2266.7, 246.0, 44.4, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(720, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, 511.5, 1638.6, 75.4, 0.0), radius: 50.0 }, 
    Trigger::Inn
)),
(721, (
    AreaTrigger::Square { position: Position::new(Map::EasternKingdoms, -4.9, -934.9, 62.5, 0.0), length: 24.6, width: 25.7, height: 11.6, yaw: 5.8 },
    Trigger::Inn
)),
(722, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -2366.7, -346.0, -1.3, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(742, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -405.3, -2645.3, 112.0, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(743, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -1051.4, -3653.8, 31.1, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(843, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, 341.4, -4684.7, 30.9, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(844, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -10487.3, -3256.9, 39.9, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(862, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -14457.0, 496.5, 39.1, 0.0), radius: 28.0 }, 
    Trigger::Inn
)),
(882, (
    AreaTrigger::Circle { position: Position::new(Map::Uldaman, -213.7, 370.6, -35.4, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -6620.5, -3765.2, 266.9, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(902, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -6606.5, -3762.2, 266.9, 0.0), radius: 12.0 }, 
    Trigger::Teleport { location: Position::new(Map::Uldaman, -214.0, 383.6, -38.8, 0.5),required_level: 30,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(922, (
    AreaTrigger::Circle { position: Position::new(Map::ZulFarrak, 1190.3, 840.6, 13.4, 0.0), radius: 20.0 }, 
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -6795.6, -2890.7, 8.9, 3.1),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(924, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -6773.5, -2889.8, 15.1, 0.0), radius: 20.0 }, 
    Trigger::Teleport { location: Position::new(Map::ZulFarrak, 1212.7, 842.0, 8.9, 0.0),required_level: 35,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(943, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -4950.7, -1595.1, -3.0, 0.0), radius: 25.0 }, 
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -5187.5, -2804.3, -8.4, 5.8),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(982, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -2372.5, -1991.6, 121.0, 0.0), radius: 35.0 }, 
    Trigger::Inn
)),
(1022, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, 898.5, 922.7, 126.8, 0.0), radius: 35.0 }, 
    Trigger::Inn
)),
(1023, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -7162.1, -3845.9, 8.8, 0.0), radius: 20.0 }, 
    Trigger::Inn
)),
(1024, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -4370.8, 3289.1, 23.8, 0.0), radius: 35.0 }, 
    Trigger::Inn
)),
(1025, (
    AreaTrigger::Square { position: Position::new(Map::Kalimdor, -4461.9, 242.6, 45.2, 0.0), length: 52.7, width: 20.5, height: 14.2, yaw: 3.6 },
    Trigger::Inn
)),
(1042, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, 357.2, -2106.1, 121.8, 0.0), radius: 60.0 }, 
    Trigger::Inn
)),
(1064, (
    AreaTrigger::Circle { position: Position::new(Map::OnyxiasLair, 29.2, -22.2, 10.5, 0.0), radius: 30.0 }, 
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -4750.4, -3754.4, 49.0, 0.8),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(1103, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -14468.0, 457.5, 16.0, 0.0), radius: 2.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -5100.9, 754.6, 260.5, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(1104, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -5096.8, 750.2, 260.5, 0.0), radius: 2.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -14461.9, 458.3, 15.2, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(1466, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -7176.6, -937.7, 170.2, 0.0), radius: 13.0 }, 
    Trigger::Teleport { location: Position::new(Map::BlackrockDepths, 456.9, 34.1, -69.6, 4.7),required_level: 40,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(1468, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -7518.2, -1239.1, 287.2, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::BlackrockSpire, 78.4, -226.8, 49.8, 4.7),required_level: 45,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(1470, (
    AreaTrigger::Circle { position: Position::new(Map::BlackrockSpire, 73.5, -215.0, 52.4, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -7524.7, -1228.4, 285.7, 1.7),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(1472, (
    AreaTrigger::Circle { position: Position::new(Map::BlackrockDepths, 457.0, 48.4, -65.3, 0.0), radius: 12.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -7178.4, -922.2, 166.1, 2.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(1606, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -6657.4, -2157.1, 264.1, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(1646, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -907.9, -3534.2, 83.8, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(2166, (
    AreaTrigger::Square { position: Position::new(Map::DeeprunTram, 76.0, 10.5, -4.3, 0.0), length: 9.4, width: 19.0, height: 20.6, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -4839.0, -1318.5, 501.9, 1.4),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2171, (
    AreaTrigger::Circle { position: Position::new(Map::DeeprunTram, 80.2, 2490.9, -1.9, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -8364.6, 536.0, 91.8, 2.2),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2173, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -8346.5, 514.0, 96.6, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::DeeprunTram, 68.3, 2490.9, -4.3, 3.1),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2175, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -4840.3, -1330.5, 508.2, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::DeeprunTram, 69.3, 10.3, -4.3, 3.1),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2214, (
    AreaTrigger::Square { position: Position::new(Map::EasternKingdoms, 3237.5, -4060.6, 112.0, 0.0), length: 10.0, width: 10.0, height: 10.0, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::Stratholme, 3590.9, -3643.2, 138.5, 5.5),required_level: 45,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2216, (
    AreaTrigger::Square { position: Position::new(Map::EasternKingdoms, 3392.5, -3396.8, 143.1, 0.0), length: 22.8, width: 8.1, height: 34.7, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::Stratholme, 3392.9, -3395.0, 143.1, 1.6),required_level: 45,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2217, (
    AreaTrigger::Square { position: Position::new(Map::EasternKingdoms, 3392.6, -3361.8, 142.8, 0.0), length: 27.9, width: 7.1, height: 35.2, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::Stratholme, 3392.8, -3364.4, 143.0, 4.7),required_level: 45,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2221, (
    AreaTrigger::Circle { position: Position::new(Map::Stratholme, 3584.8, -3632.1, 142.1, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, 3233.1, -4048.3, 108.4, 2.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2226, (
    AreaTrigger::Square { position: Position::new(Map::RagefireChasm, 2.6, -0.0, -13.4, 0.0), length: 30.7, width: 12.2, height: 25.6, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::Kalimdor, 1815.0, -4419.2, -18.8, 1.9),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2230, (
    AreaTrigger::Square { position: Position::new(Map::Kalimdor, 1818.4, -4427.3, -10.4, 0.0), length: 21.7, width: 11.8, height: 21.2, yaw: 0.6 },
    Trigger::Teleport { location: Position::new(Map::RagefireChasm, 0.8, -8.2, -15.5, 4.7),required_level: 8,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2266, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, 245.6, 1252.0, 210.1, 0.0), radius: 40.0 }, 
    Trigger::Inn
)),
(2267, (
    AreaTrigger::Square { position: Position::new(Map::Kalimdor, -1596.2, 3145.3, 61.4, 0.0), length: 30.0, width: 30.0, height: 30.0, yaw: 0.0 },
    Trigger::Inn
)),
(2286, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -5477.9, -2460.3, 89.3, 0.0), radius: 20.0 }, 
    Trigger::Inn
)),
(2287, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, 6688.0, -4670.1, 723.9, 0.0), radius: 20.0 }, 
    Trigger::Inn
)),
(2406, (
    AreaTrigger::Square { position: Position::new(Map::ShadowfangKeep, -287.1, 2175.6, 36.9, 0.0), length: 98.9, width: 185.6, height: 80.6, yaw: 2.9 },
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -233.0, 1567.5, 76.9, 4.3),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2530, (
    AreaTrigger::Square { position: Position::new(Map::HordePvpBarracks, 215.2, 71.2, 30.1, 0.0), length: 10.0, width: 10.0, height: 10.0, yaw: 3.6 },
    Trigger::Teleport { location: Position::new(Map::Kalimdor, 1637.3, -4242.7, 56.2, 4.2),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2534, (
    AreaTrigger::Square { position: Position::new(Map::AlliancePvpBarracks, -0.2, -1.6, -0.3, 0.0), length: 4.8, width: 4.9, height: 8.2, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -8762.5, 403.1, 103.9, 5.3),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2567, (
    AreaTrigger::Square { position: Position::new(Map::EasternKingdoms, 1282.1, -2548.7, 85.4, 0.0), length: 10.6, width: 13.0, height: 21.7, yaw: 0.5 },
    Trigger::Teleport { location: Position::new(Map::Scholomance, 190.8, 126.3, 137.2, 0.0),required_level: 45,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2568, (
    AreaTrigger::Square { position: Position::new(Map::Scholomance, 182.3, 126.4, 143.7, 0.0), length: 12.3, width: 8.9, height: 16.4, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, 1273.9, -2553.1, 90.6, 3.6),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2606, (
    AreaTrigger::Square { position: Position::new(Map::AlteracValley, -723.6, -707.6, 52.9, 0.0), length: 9.6, width: 14.1, height: 16.2, yaw: 5.3 },
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, 534.9, -1087.7, 106.1, 3.4),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2608, (
    AreaTrigger::Square { position: Position::new(Map::AlteracValley, 946.8, -500.1, 94.9, 0.0), length: 8.7, width: 18.3, height: 24.3, yaw: 1.1 },
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, 98.4, -182.3, 127.5, 5.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2610, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, 2343.6, -2569.0, 118.8, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(2786, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -9050.9, 445.5, 93.1, 0.0), radius: 1.0 }, 
    Trigger::Inn
)),
(2848, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -4768.6, -3752.1, 53.4, 0.0), radius: 16.0 }, 
    Trigger::Teleport { location: Position::new(Map::OnyxiasLair, 30.9, -54.1, -5.0, 4.7),required_level: 50,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2886, (
    AreaTrigger::Circle { position: Position::new(Map::BlackrockDepths, 1098.0, -466.5, -96.1, 0.0), radius: 20.0 }, 
    Trigger::Teleport { location: Position::new(Map::MoltenCore, 1096.0, -467.0, -104.6, 3.6),required_level: 50,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(2890, (
    AreaTrigger::Circle { position: Position::new(Map::MoltenCore, 1115.2, -463.0, -95.0, 0.0), radius: 20.0 }, 
    Trigger::Teleport { location: Position::new(Map::BlackrockDepths, 1115.3, -457.4, -102.7, 0.5),required_level: 50,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3126, (
    AreaTrigger::Square { position: Position::new(Map::Maraudon, 756.9, -634.0, -32.8, 0.0), length: 15.9, width: 26.4, height: 44.1, yaw: 1.6 },
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -1182.8, 2877.4, 85.9, 1.7),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3131, (
    AreaTrigger::Square { position: Position::new(Map::Maraudon, 1005.0, -460.5, -43.3, 0.0), length: 10.1, width: 31.4, height: 23.4, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -1468.2, 2614.2, 76.4, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3133, (
    AreaTrigger::Square { position: Position::new(Map::Kalimdor, -1484.1, 2617.6, 75.7, 0.0), length: 24.7, width: 15.8, height: 35.2, yaw: 4.5 },
    Trigger::Teleport { location: Position::new(Map::Maraudon, 1016.8, -458.5, -43.5, 0.0),required_level: 35,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3134, (
    AreaTrigger::Square { position: Position::new(Map::Kalimdor, -1182.0, 2861.9, 85.3, 0.0), length: 31.7, width: 17.3, height: 34.2, yaw: 3.2 },
    Trigger::Teleport { location: Position::new(Map::Maraudon, 755.1, -617.7, -32.9, 1.6),required_level: 35,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3183, (
    AreaTrigger::Square { position: Position::new(Map::Kalimdor, -3730.5, 934.0, 161.0, 0.0), length: 9.4, width: 12.8, height: 19.7, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::DireMaul, 47.5, -153.7, -2.7, 5.5),required_level: 45,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3184, (
    AreaTrigger::Square { position: Position::new(Map::Kalimdor, -3981.6, 771.2, 161.0, 0.0), length: 10.3, width: 6.0, height: 20.2, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::DireMaul, -201.1, -328.7, -2.7, 5.2),required_level: 45,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3185, (
    AreaTrigger::Square { position: Position::new(Map::Kalimdor, -4028.2, 124.0, 26.8, 0.0), length: 9.8, width: 4.6, height: 15.7, yaw: 0.5 },
    Trigger::Teleport { location: Position::new(Map::DireMaul, 10.6, -837.0, -32.4, 0.0),required_level: 45,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3186, (
    AreaTrigger::Square { position: Position::new(Map::Kalimdor, -3837.8, 1250.2, 160.2, 0.0), length: 8.2, width: 9.1, height: 18.4, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::DireMaul, -65.7, 159.6, -3.5, 2.4),required_level: 45,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3187, (
    AreaTrigger::Square { position: Position::new(Map::Kalimdor, -3742.0, 1249.2, 160.2, 0.0), length: 7.9, width: 10.3, height: 18.7, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::DireMaul, 33.1, 159.0, -3.5, 0.8),required_level: 45,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3189, (
    AreaTrigger::Square { position: Position::new(Map::Kalimdor, -3520.6, 1068.7, 161.1, 0.0), length: 9.9, width: 11.9, height: 23.2, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::DireMaul, 254.9, -19.5, -2.6, 5.5),required_level: 45,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3190, (
    AreaTrigger::Square { position: Position::new(Map::DireMaul, -56.0, 159.9, -3.5, 0.0), length: 7.2, width: 10.1, height: 19.6, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -3831.8, 1250.2, 160.2, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3191, (
    AreaTrigger::Square { position: Position::new(Map::DireMaul, 24.6, 159.4, -3.5, 0.0), length: 7.7, width: 9.7, height: 21.6, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -3748.0, 1249.2, 160.2, 3.2),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3193, (
    AreaTrigger::Square { position: Position::new(Map::DireMaul, 255.2, -9.1, -2.6, 0.0), length: 8.3, width: 8.6, height: 20.7, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -3520.6, 1077.7, 161.1, 1.5),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3194, (
    AreaTrigger::Square { position: Position::new(Map::DireMaul, 37.4, -154.8, -2.7, 0.0), length: 8.9, width: 9.2, height: 19.4, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -3738.6, 934.5, 161.0, 3.1),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3195, (
    AreaTrigger::Square { position: Position::new(Map::DireMaul, -202.7, -314.9, -2.7, 0.0), length: 9.8, width: 10.2, height: 17.4, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -3980.6, 776.2, 161.0, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3196, (
    AreaTrigger::Square { position: Position::new(Map::DireMaul, 4.3, -837.1, -33.0, 0.0), length: 6.2, width: 11.4, height: 22.9, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -4031.2, 129.3, 26.5, 1.6),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3197, (
    AreaTrigger::Square { position: Position::new(Map::DireMaul, 194.4, -240.8, -25.6, 0.0), length: 12.9, width: 8.3, height: 25.3, yaw: 1.1 },
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -3585.8, 847.4, 138.6, 2.4),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3528, (
    AreaTrigger::Square { position: Position::new(Map::EasternKingdoms, -7510.9, -1035.9, 183.0, 0.0), length: 3.8, width: 0.4, height: 2.1, yaw: 0.7 },
    Trigger::Teleport { location: Position::new(Map::MoltenCore, 1096.0, -467.0, -104.6, 3.6),required_level: 50,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3529, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -7512.2, -1034.8, 177.2, 0.0), radius: 4.0 }, 
    Trigger::Teleport { location: Position::new(Map::MoltenCore, 1096.0, -467.0, -104.6, 3.6),required_level: 50,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3547, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, 1642.1, 239.8, 62.6, 0.0), radius: 13.0 }, 
    Trigger::Inn
)),
(3690, (
    AreaTrigger::Square { position: Position::new(Map::EasternKingdoms, -622.1, -4582.1, 22.6, 0.0), length: 27.4, width: 27.2, height: 21.6, yaw: 3.2 },
    Trigger::Inn
)),
(3726, (
    AreaTrigger::Square { position: Position::new(Map::BlackrockSpire, 178.7, -474.4, 120.6, 0.0), length: 3.8, width: 7.9, height: 7.9, yaw: 0.0 },
    Trigger::Teleport { location: Position::new(Map::BlackwingLair, -7672.3, -1107.1, 396.7, 0.8),required_level: 60,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3728, (
    AreaTrigger::Square { position: Position::new(Map::BlackwingLair, -7676.1, -1109.7, 399.1, 0.0), length: 2.5, width: 8.7, height: 5.1, yaw: 3.8 },
    Trigger::Teleport { location: Position::new(Map::BlackrockSpire, 174.7, -474.8, 116.8, 3.2),required_level: 45,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3886, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -12432.8, 205.2, 2.4, 0.0), radius: 18.0 }, 
    Trigger::Inn
)),
(3928, (
    AreaTrigger::Circle { position: Position::new(Map::EasternKingdoms, -11915.8, -1236.4, 96.2, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::ZulGurub, -11916.6, -1243.5, 92.5, 4.7),required_level: 50,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3930, (
    AreaTrigger::Circle { position: Position::new(Map::ZulGurub, -11917.0, -1221.0, 97.6, 0.0), radius: 10.0 }, 
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -11916.3, -1208.4, 92.3, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3948, (
    AreaTrigger::Square { position: Position::new(Map::ArathiBasin, 1394.4, 1303.6, -8.0, 0.0), length: 7.3, width: 16.9, height: 17.6, yaw: 0.4 },
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -1198.0, -2533.0, 22.0, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3949, (
    AreaTrigger::Square { position: Position::new(Map::ArathiBasin, 627.2, 700.0, -12.0, 0.0), length: 7.9, width: 14.2, height: 17.3, yaw: 3.3 },
    Trigger::Teleport { location: Position::new(Map::EasternKingdoms, -817.0, -3509.0, 73.0, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(3985, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, -6865.0, 731.6, 50.0, 0.0), radius: 20.0 }, 
    Trigger::Inn
)),
(4006, (
    AreaTrigger::Square { position: Position::new(Map::RuinsOfAhnQiraj, -8419.6, 1504.3, 31.7, 0.0), length: 18.0, width: 41.8, height: 40.5, yaw: 5.8 },
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -8418.5, 1505.9, 31.8, 0.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(4008, (
    AreaTrigger::Square { position: Position::new(Map::Kalimdor, -8424.9, 1508.7, 32.0, 0.0), length: 12.1, width: 50.1, height: 35.6, yaw: 2.6 },
    Trigger::Teleport { location: Position::new(Map::RuinsOfAhnQiraj, -8436.5, 1519.2, 31.9, 2.6),required_level: 50,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(4010, (
    AreaTrigger::Square { position: Position::new(Map::Kalimdor, -8230.4, 2005.3, 129.9, 0.0), length: 16.7, width: 31.2, height: 46.6, yaw: 0.9 },
    Trigger::Teleport { location: Position::new(Map::AhnQirajTemple, -8221.3, 2014.3, 129.1, 0.9),required_level: 50,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(4012, (
    AreaTrigger::Square { position: Position::new(Map::AhnQirajTemple, -8231.3, 2003.6, 129.9, 0.0), length: 38.9, width: 10.3, height: 81.6, yaw: 5.7 },
    Trigger::Teleport { location: Position::new(Map::Kalimdor, -8239.0, 1993.2, 129.1, 4.0),required_level: 0,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
(4058, (
    AreaTrigger::Square { position: Position::new(Map::EasternKingdoms, 2298.2, -5341.0, 90.9, 0.0), length: 33.5, width: 17.7, height: 24.6, yaw: 2.2 },
    Trigger::Inn
)),
(4090, (
    AreaTrigger::Circle { position: Position::new(Map::Kalimdor, 2716.6, 1496.8, 236.8, 0.0), radius: 30.0 }, 
    Trigger::Inn
)),
(4156, (
    AreaTrigger::Circle { position: Position::new(Map::Naxxramas, 3006.1, -3434.2, 306.2, 0.0), radius: 6.0 }, 
    Trigger::Teleport { location: Position::new(Map::Naxxramas, 3498.3, -5349.9, 145.0, 1.3),required_level: 80,required_item: 0,required_quest: 0,failed_text: None,
heroic_keys: None,heroic_required_quest: 0 }
)),
// AUTOGENERATED_END
];
