use crate::extended::tbc::tbc_race_class_match;
use crate::tbc::RaceClass;
use crate::tbc::Skill;

tbc_race_class_match!(starter_skills, &'static [Skill], RaceClass);

// AUTOGENERATED_START
const HUMAN_WARRIOR: &[Skill] = &[
    Skill::Arms, // Warrior: Arms
    Skill::Swords, // Weapon: Swords (Warrior)
    Skill::Axes, // Weapon: Axes (Warrior)
    Skill::Maces, // Weapon: Maces (Warrior)
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Fury, // Warrior: Fury
    Skill::Protection, // Warrior: Protection
    Skill::Mail, // Armor: Mail
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
    Skill::RacialHuman, // Racial: Human
];
const HUMAN_PALADIN: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Paladin)
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::TwoHandedMaces, // Weapon: Two-Handed Maces (Paladin)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Retribution, // Paladin: Retribution
    Skill::Protection2, // Paladin: Protection
    Skill::Mail, // Armor: Mail
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
    Skill::Holy2, // Paladin: Holy
    Skill::RacialHuman, // Racial: Human
];
const HUMAN_ROGUE: &[Skill] = &[
    Skill::Combat, // Rogue: Combat
    Skill::Subtlety, // Rogue: Subtlety
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Rogue)
    Skill::Thrown, // Weapon: Thrown (Rogue)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Assassination, // Rogue: Assassination
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::RacialHuman, // Racial: Human
];
const HUMAN_PRIEST: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Priest)
    Skill::Holy, // Priest: Holy
    Skill::Shadow, // Priest: Shadow
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Priest)
    Skill::Cloth, // Armor: Cloth
    Skill::Discipline, // Priest: Discipline
    Skill::RacialHuman, // Racial: Human
];
const HUMAN_MAGE: &[Skill] = &[
    Skill::Frost, // Mage: Frost
    Skill::Fire, // Mage: Fire
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Staves, // Weapon: Staves (Mage)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Mage)
    Skill::Arcane, // Mage: Arcane
    Skill::Cloth, // Armor: Cloth
    Skill::RacialHuman, // Racial: Human
];
const HUMAN_WARLOCK: &[Skill] = &[
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Warlock)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Warlock)
    Skill::Demonology, // Warlock: Demonology
    Skill::Affliction, // Warlock: Affliction
    Skill::Cloth, // Armor: Cloth
    Skill::Destruction, // Warlock: Destruction
    Skill::RacialHuman, // Racial: Human
];
const ORC_WARRIOR: &[Skill] = &[
    Skill::Arms, // Warrior: Arms
    Skill::Swords, // Weapon: Swords (Warrior)
    Skill::Axes, // Weapon: Axes (Warrior)
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::OrcRacial, // Racial: Orc
    Skill::Unarmed, // Weapon: Unarmed
    Skill::TwoHandedAxes, // Weapon: Two-Handed Axes (Warrior)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Fury, // Warrior: Fury
    Skill::Protection, // Warrior: Protection
    Skill::Mail, // Armor: Mail
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
];
const ORC_HUNTER: &[Skill] = &[
    Skill::Axes, // Weapon: Axes (Hunter)
    Skill::Bows, // Weapon: Bows (Hunter)
    Skill::BeastMastery, // Hunter: Beast Mastery
    Skill::Survival, // Hunter: Survival
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::OrcRacial, // Racial: Orc
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Marksmanship, // Hunter: Marksmanship
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
];
const ORC_ROGUE: &[Skill] = &[
    Skill::Combat, // Rogue: Combat
    Skill::Subtlety, // Rogue: Subtlety
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::OrcRacial, // Racial: Orc
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Rogue)
    Skill::Thrown, // Weapon: Thrown (Rogue)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Assassination, // Rogue: Assassination
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
];
const ORC_SHAMAN: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Shaman)
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::OrcRacial, // Racial: Orc
    Skill::Staves, // Weapon: Staves (Shaman)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Enhancement, // Shaman: Enhancement
    Skill::Restoration, // Shaman: Restoration
    Skill::ElementalCombat, // Shaman: Elemental
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
];
const ORC_WARLOCK: &[Skill] = &[
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::OrcRacial, // Racial: Orc
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Warlock)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Warlock)
    Skill::Demonology, // Warlock: Demonology
    Skill::Affliction, // Warlock: Affliction
    Skill::Cloth, // Armor: Cloth
    Skill::Destruction, // Warlock: Destruction
];
const DWARF_WARRIOR: &[Skill] = &[
    Skill::Arms, // Warrior: Arms
    Skill::Axes, // Weapon: Axes (Warrior)
    Skill::Maces, // Weapon: Maces (Warrior)
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::RacialDwarven, // Racial: Dwarf
    Skill::LanguageDwarven, // Language: Dwarven
    Skill::Unarmed, // Weapon: Unarmed
    Skill::TwoHandedAxes, // Weapon: Two-Handed Axes (Warrior)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Fury, // Warrior: Fury
    Skill::Protection, // Warrior: Protection
    Skill::Mail, // Armor: Mail
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
];
const DWARF_PALADIN: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Paladin)
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::RacialDwarven, // Racial: Dwarf
    Skill::LanguageDwarven, // Language: Dwarven
    Skill::TwoHandedMaces, // Weapon: Two-Handed Maces (Paladin)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Retribution, // Paladin: Retribution
    Skill::Protection2, // Paladin: Protection
    Skill::Mail, // Armor: Mail
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
    Skill::Holy2, // Paladin: Holy
];
const DWARF_HUNTER: &[Skill] = &[
    Skill::Axes, // Weapon: Axes (Hunter)
    Skill::Guns, // Weapon: Guns (Hunter)
    Skill::BeastMastery, // Hunter: Beast Mastery
    Skill::Survival, // Hunter: Survival
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::RacialDwarven, // Racial: Dwarf
    Skill::LanguageDwarven, // Language: Dwarven
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Marksmanship, // Hunter: Marksmanship
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
];
const DWARF_ROGUE: &[Skill] = &[
    Skill::Combat, // Rogue: Combat
    Skill::Subtlety, // Rogue: Subtlety
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::RacialDwarven, // Racial: Dwarf
    Skill::LanguageDwarven, // Language: Dwarven
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Rogue)
    Skill::Thrown, // Weapon: Thrown (Rogue)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Assassination, // Rogue: Assassination
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
];
const DWARF_PRIEST: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Priest)
    Skill::Holy, // Priest: Holy
    Skill::Shadow, // Priest: Shadow
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::RacialDwarven, // Racial: Dwarf
    Skill::LanguageDwarven, // Language: Dwarven
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Priest)
    Skill::Cloth, // Armor: Cloth
    Skill::Discipline, // Priest: Discipline
];
const NIGHT_ELF_WARRIOR: &[Skill] = &[
    Skill::Arms, // Warrior: Arms
    Skill::Swords, // Weapon: Swords (Warrior)
    Skill::Maces, // Weapon: Maces (Warrior)
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::LanguageDarnassian, // Language: Darnassian
    Skill::RacialNightElf, // Racial: Night Elf
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Warrior)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Fury, // Warrior: Fury
    Skill::Protection, // Warrior: Protection
    Skill::Mail, // Armor: Mail
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
];
const NIGHT_ELF_HUNTER: &[Skill] = &[
    Skill::Bows, // Weapon: Bows (Hunter)
    Skill::BeastMastery, // Hunter: Beast Mastery
    Skill::Survival, // Hunter: Survival
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::LanguageDarnassian, // Language: Darnassian
    Skill::RacialNightElf, // Racial: Night Elf
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Marksmanship, // Hunter: Marksmanship
    Skill::Daggers, // Weapon: Daggers (Hunter)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
];
const NIGHT_ELF_ROGUE: &[Skill] = &[
    Skill::Combat, // Rogue: Combat
    Skill::Subtlety, // Rogue: Subtlety
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::LanguageDarnassian, // Language: Darnassian
    Skill::RacialNightElf, // Racial: Night Elf
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Rogue)
    Skill::Thrown, // Weapon: Thrown (Rogue)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Assassination, // Rogue: Assassination
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
];
const NIGHT_ELF_PRIEST: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Priest)
    Skill::Holy, // Priest: Holy
    Skill::Shadow, // Priest: Shadow
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::LanguageDarnassian, // Language: Darnassian
    Skill::RacialNightElf, // Racial: Night Elf
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Priest)
    Skill::Cloth, // Armor: Cloth
    Skill::Discipline, // Priest: Discipline
];
const NIGHT_ELF_DRUID: &[Skill] = &[
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::LanguageDarnassian, // Language: Darnassian
    Skill::RacialNightElf, // Racial: Night Elf
    Skill::FeralCombat, // Druid: Feral Combat
    Skill::Staves, // Weapon: Staves (Druid)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Druid)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Restoration2, // Druid: Restoration
    Skill::Balance, // Druid: Balance
];
const UNDEAD_WARRIOR: &[Skill] = &[
    Skill::Arms, // Warrior: Arms
    Skill::Swords, // Weapon: Swords (Warrior)
    Skill::TwoHandedSwords, // Weapon: Two-Handed Swords (Warrior)
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Warrior)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::RacialUnded, // Racial: Undead
    Skill::Fury, // Warrior: Fury
    Skill::Protection, // Warrior: Protection
    Skill::Mail, // Armor: Mail
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
    Skill::LanguageGutterspeak, // Language: Gutterspeak
];
const UNDEAD_ROGUE: &[Skill] = &[
    Skill::Combat, // Rogue: Combat
    Skill::Subtlety, // Rogue: Subtlety
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Rogue)
    Skill::Thrown, // Weapon: Thrown (Rogue)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::RacialUnded, // Racial: Undead
    Skill::Assassination, // Rogue: Assassination
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::LanguageGutterspeak, // Language: Gutterspeak
];
const UNDEAD_PRIEST: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Priest)
    Skill::Holy, // Priest: Holy
    Skill::Shadow, // Priest: Shadow
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::RacialUnded, // Racial: Undead
    Skill::Wands, // Weapon: Wands (Priest)
    Skill::Cloth, // Armor: Cloth
    Skill::Discipline, // Priest: Discipline
    Skill::LanguageGutterspeak, // Language: Gutterspeak
];
const UNDEAD_MAGE: &[Skill] = &[
    Skill::Frost, // Mage: Frost
    Skill::Fire, // Mage: Fire
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::Staves, // Weapon: Staves (Mage)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::RacialUnded, // Racial: Undead
    Skill::Wands, // Weapon: Wands (Mage)
    Skill::Arcane, // Mage: Arcane
    Skill::Cloth, // Armor: Cloth
    Skill::LanguageGutterspeak, // Language: Gutterspeak
];
const UNDEAD_WARLOCK: &[Skill] = &[
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Warlock)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::RacialUnded, // Racial: Undead
    Skill::Wands, // Weapon: Wands (Warlock)
    Skill::Demonology, // Warlock: Demonology
    Skill::Affliction, // Warlock: Affliction
    Skill::Cloth, // Armor: Cloth
    Skill::Destruction, // Warlock: Destruction
    Skill::LanguageGutterspeak, // Language: Gutterspeak
];
const TAUREN_WARRIOR: &[Skill] = &[
    Skill::Arms, // Warrior: Arms
    Skill::Axes, // Weapon: Axes (Warrior)
    Skill::Maces, // Weapon: Maces (Warrior)
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::LanguageTaurahe, // Language: Taurahe
    Skill::RacialTauren, // Racial: Tauren
    Skill::TwoHandedMaces, // Weapon: Two-Handed Maces (Warrior)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Fury, // Warrior: Fury
    Skill::Protection, // Warrior: Protection
    Skill::Mail, // Armor: Mail
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
];
const TAUREN_HUNTER: &[Skill] = &[
    Skill::Axes, // Weapon: Axes (Hunter)
    Skill::Guns, // Weapon: Guns (Hunter)
    Skill::BeastMastery, // Hunter: Beast Mastery
    Skill::Survival, // Hunter: Survival
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::LanguageTaurahe, // Language: Taurahe
    Skill::RacialTauren, // Racial: Tauren
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Marksmanship, // Hunter: Marksmanship
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
];
const TAUREN_SHAMAN: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Shaman)
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::LanguageTaurahe, // Language: Taurahe
    Skill::RacialTauren, // Racial: Tauren
    Skill::Staves, // Weapon: Staves (Shaman)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Enhancement, // Shaman: Enhancement
    Skill::Restoration, // Shaman: Restoration
    Skill::ElementalCombat, // Shaman: Elemental
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
];
const TAUREN_DRUID: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Druid)
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::LanguageTaurahe, // Language: Taurahe
    Skill::RacialTauren, // Racial: Tauren
    Skill::FeralCombat, // Druid: Feral Combat
    Skill::Staves, // Weapon: Staves (Druid)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Restoration2, // Druid: Restoration
    Skill::Balance, // Druid: Balance
];
const GNOME_WARRIOR: &[Skill] = &[
    Skill::Arms, // Warrior: Arms
    Skill::Swords, // Weapon: Swords (Warrior)
    Skill::Maces, // Weapon: Maces (Warrior)
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Warrior)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Fury, // Warrior: Fury
    Skill::Protection, // Warrior: Protection
    Skill::LanguageGnomish, // Language: Gnomish
    Skill::Mail, // Armor: Mail
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
    Skill::RacialGnome, // Racial: Gnome
];
const GNOME_ROGUE: &[Skill] = &[
    Skill::Combat, // Rogue: Combat
    Skill::Subtlety, // Rogue: Subtlety
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Rogue)
    Skill::Thrown, // Weapon: Thrown (Rogue)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Assassination, // Rogue: Assassination
    Skill::LanguageGnomish, // Language: Gnomish
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::RacialGnome, // Racial: Gnome
];
const GNOME_MAGE: &[Skill] = &[
    Skill::Frost, // Mage: Frost
    Skill::Fire, // Mage: Fire
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Staves, // Weapon: Staves (Mage)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Mage)
    Skill::Arcane, // Mage: Arcane
    Skill::LanguageGnomish, // Language: Gnomish
    Skill::Cloth, // Armor: Cloth
    Skill::RacialGnome, // Racial: Gnome
];
const GNOME_WARLOCK: &[Skill] = &[
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Warlock)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Warlock)
    Skill::LanguageGnomish, // Language: Gnomish
    Skill::Demonology, // Warlock: Demonology
    Skill::Affliction, // Warlock: Affliction
    Skill::Cloth, // Armor: Cloth
    Skill::Destruction, // Warlock: Destruction
    Skill::RacialGnome, // Racial: Gnome
];
const TROLL_WARRIOR: &[Skill] = &[
    Skill::Arms, // Warrior: Arms
    Skill::Axes, // Weapon: Axes (Warrior)
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Warrior)
    Skill::Thrown, // Weapon: Thrown (Warrior)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Fury, // Warrior: Fury
    Skill::Protection, // Warrior: Protection
    Skill::LanguageTroll, // Language: Troll
    Skill::Mail, // Armor: Mail
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
    Skill::RacialTroll, // Racial: Troll
];
const TROLL_HUNTER: &[Skill] = &[
    Skill::Axes, // Weapon: Axes (Hunter)
    Skill::Bows, // Weapon: Bows (Hunter)
    Skill::BeastMastery, // Hunter: Beast Mastery
    Skill::Survival, // Hunter: Survival
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Marksmanship, // Hunter: Marksmanship
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::LanguageTroll, // Language: Troll
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::RacialTroll, // Racial: Troll
];
const TROLL_ROGUE: &[Skill] = &[
    Skill::Combat, // Rogue: Combat
    Skill::Subtlety, // Rogue: Subtlety
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Rogue)
    Skill::Thrown, // Weapon: Thrown (Rogue)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Assassination, // Rogue: Assassination
    Skill::LanguageTroll, // Language: Troll
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::RacialTroll, // Racial: Troll
];
const TROLL_PRIEST: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Priest)
    Skill::Holy, // Priest: Holy
    Skill::Shadow, // Priest: Shadow
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Priest)
    Skill::LanguageTroll, // Language: Troll
    Skill::Cloth, // Armor: Cloth
    Skill::Discipline, // Priest: Discipline
    Skill::RacialTroll, // Racial: Troll
];
const TROLL_SHAMAN: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Shaman)
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::Staves, // Weapon: Staves (Shaman)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::LanguageTroll, // Language: Troll
    Skill::Enhancement, // Shaman: Enhancement
    Skill::Restoration, // Shaman: Restoration
    Skill::ElementalCombat, // Shaman: Elemental
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
    Skill::RacialTroll, // Racial: Troll
];
const TROLL_MAGE: &[Skill] = &[
    Skill::Frost, // Mage: Frost
    Skill::Fire, // Mage: Fire
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::Staves, // Weapon: Staves (Mage)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Mage)
    Skill::Arcane, // Mage: Arcane
    Skill::LanguageTroll, // Language: Troll
    Skill::Cloth, // Armor: Cloth
    Skill::RacialTroll, // Racial: Troll
];
const BLOOD_ELF_PALADIN: &[Skill] = &[
    Skill::Swords, // Weapon: Swords (Paladin)
    Skill::TwoHandedSwords, // Weapon: Two-Handed Swords (Paladin)
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::LanguageThalassian, // Language: Thalassian
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Retribution, // Paladin: Retribution
    Skill::Protection2, // Paladin: Protection
    Skill::Mail, // Armor: Mail
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
    Skill::Holy2, // Paladin: Holy
    Skill::RacialBloodelf, // Racial: Blood Elf
];
const BLOOD_ELF_HUNTER: &[Skill] = &[
    Skill::Bows, // Weapon: Bows (Hunter)
    Skill::BeastMastery, // Hunter: Beast Mastery
    Skill::Survival, // Hunter: Survival
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::LanguageThalassian, // Language: Thalassian
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Marksmanship, // Hunter: Marksmanship
    Skill::Daggers, // Weapon: Daggers (Hunter)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::RacialBloodelf, // Racial: Blood Elf
];
const BLOOD_ELF_ROGUE: &[Skill] = &[
    Skill::Combat, // Rogue: Combat
    Skill::Subtlety, // Rogue: Subtlety
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::LanguageThalassian, // Language: Thalassian
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Rogue)
    Skill::Thrown, // Weapon: Thrown (Rogue)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Assassination, // Rogue: Assassination
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::RacialBloodelf, // Racial: Blood Elf
];
const BLOOD_ELF_PRIEST: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Priest)
    Skill::Holy, // Priest: Holy
    Skill::Shadow, // Priest: Shadow
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::LanguageThalassian, // Language: Thalassian
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Priest)
    Skill::Cloth, // Armor: Cloth
    Skill::Discipline, // Priest: Discipline
    Skill::RacialBloodelf, // Racial: Blood Elf
];
const BLOOD_ELF_MAGE: &[Skill] = &[
    Skill::Frost, // Mage: Frost
    Skill::Fire, // Mage: Fire
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::Staves, // Weapon: Staves (Mage)
    Skill::LanguageThalassian, // Language: Thalassian
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Mage)
    Skill::Arcane, // Mage: Arcane
    Skill::Cloth, // Armor: Cloth
    Skill::RacialBloodelf, // Racial: Blood Elf
];
const BLOOD_ELF_WARLOCK: &[Skill] = &[
    Skill::Defense, // Misc: Defense
    Skill::LanguageOrcish, // Language: Orcish
    Skill::LanguageThalassian, // Language: Thalassian
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Daggers, // Weapon: Daggers (Warlock)
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Warlock)
    Skill::Demonology, // Warlock: Demonology
    Skill::Affliction, // Warlock: Affliction
    Skill::Cloth, // Armor: Cloth
    Skill::Destruction, // Warlock: Destruction
    Skill::RacialBloodelf, // Racial: Blood Elf
];
const DRAENEI_WARRIOR: &[Skill] = &[
    Skill::Arms, // Warrior: Arms
    Skill::Swords, // Weapon: Swords (Warrior)
    Skill::Maces, // Weapon: Maces (Warrior)
    Skill::TwoHandedSwords, // Weapon: Two-Handed Swords (Warrior)
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Fury, // Warrior: Fury
    Skill::Protection, // Warrior: Protection
    Skill::Mail, // Armor: Mail
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
    Skill::LanguageDraenei, // Language: Draenei
    Skill::RacialDraenei, // Racial: Draenei
];
const DRAENEI_PALADIN: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Paladin)
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::TwoHandedMaces, // Weapon: Two-Handed Maces (Paladin)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Retribution, // Paladin: Retribution
    Skill::Protection2, // Paladin: Protection
    Skill::Mail, // Armor: Mail
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
    Skill::Holy2, // Paladin: Holy
    Skill::LanguageDraenei, // Language: Draenei
    Skill::RacialDraenei, // Racial: Draenei
];
const DRAENEI_HUNTER: &[Skill] = &[
    Skill::Swords, // Weapon: Swords (Hunter)
    Skill::BeastMastery, // Hunter: Beast Mastery
    Skill::Survival, // Hunter: Survival
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Unarmed, // Weapon: Unarmed
    Skill::Marksmanship, // Hunter: Marksmanship
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Crossbows, // Weapon: Crossbows (Hunter)
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::LanguageDraenei, // Language: Draenei
    Skill::RacialDraenei, // Racial: Draenei
];
const DRAENEI_PRIEST: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Priest)
    Skill::Holy, // Priest: Holy
    Skill::Shadow, // Priest: Shadow
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Priest)
    Skill::Cloth, // Armor: Cloth
    Skill::Discipline, // Priest: Discipline
    Skill::LanguageDraenei, // Language: Draenei
    Skill::RacialDraenei, // Racial: Draenei
];
const DRAENEI_SHAMAN: &[Skill] = &[
    Skill::Maces, // Weapon: Maces (Shaman)
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Staves, // Weapon: Staves (Shaman)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Enhancement, // Shaman: Enhancement
    Skill::Restoration, // Shaman: Restoration
    Skill::ElementalCombat, // Shaman: Elemental
    Skill::Leather, // Armor: Leather
    Skill::Cloth, // Armor: Cloth
    Skill::Shield, // Armor: Shield
    Skill::LanguageDraenei, // Language: Draenei
    Skill::RacialDraenei, // Racial: Draenei
];
const DRAENEI_MAGE: &[Skill] = &[
    Skill::Frost, // Mage: Frost
    Skill::Fire, // Mage: Fire
    Skill::Defense, // Misc: Defense
    Skill::LanguageCommon, // Language: Common
    Skill::Staves, // Weapon: Staves (Mage)
    Skill::Unarmed, // Weapon: Unarmed
    Skill::GenericDnd, // Misc: GENERIC (DND)
    Skill::Wands, // Weapon: Wands (Mage)
    Skill::Arcane, // Mage: Arcane
    Skill::Cloth, // Armor: Cloth
    Skill::LanguageDraenei, // Language: Draenei
    Skill::RacialDraenei, // Racial: Draenei
];
// AUTOGENERATED_END
