use crate::shared::Action;
use wow_world_base::vanilla::RaceClass;

pub const fn starter_actions(combo: RaceClass) -> &'static [Action] {
    match combo {
        RaceClass::DwarfHunter => DWARF_HUNTER,
        RaceClass::DwarfPaladin => DWARF_PALADIN,
        RaceClass::DwarfPriest => DWARF_PRIEST,
        RaceClass::DwarfRogue => DWARF_ROGUE,
        RaceClass::DwarfWarrior => DWARF_WARRIOR,
        RaceClass::GnomeMage => GNOME_MAGE,
        RaceClass::GnomeRogue => GNOME_ROGUE,
        RaceClass::GnomeWarlock => GNOME_WARLOCK,
        RaceClass::GnomeWarrior => GNOME_WARRIOR,
        RaceClass::HumanMage => HUMAN_MAGE,
        RaceClass::HumanPaladin => HUMAN_PALADIN,
        RaceClass::HumanPriest => HUMAN_PRIEST,
        RaceClass::HumanRogue => HUMAN_ROGUE,
        RaceClass::HumanWarlock => HUMAN_WARLOCK,
        RaceClass::HumanWarrior => HUMAN_WARRIOR,
        RaceClass::NightElfDruid => NIGHT_ELF_DRUID,
        RaceClass::NightElfHunter => NIGHT_ELF_HUNTER,
        RaceClass::NightElfPriest => NIGHT_ELF_PRIEST,
        RaceClass::NightElfRogue => NIGHT_ELF_ROGUE,
        RaceClass::NightElfWarrior => NIGHT_ELF_WARRIOR,
        RaceClass::OrcHunter => ORC_HUNTER,
        RaceClass::OrcRogue => ORC_ROGUE,
        RaceClass::OrcShaman => ORC_SHAMAN,
        RaceClass::OrcWarlock => ORC_WARLOCK,
        RaceClass::OrcWarrior => ORC_WARRIOR,
        RaceClass::TaurenDruid => TAUREN_DRUID,
        RaceClass::TaurenHunter => TAUREN_HUNTER,
        RaceClass::TaurenShaman => TAUREN_SHAMAN,
        RaceClass::TaurenWarrior => TAUREN_WARRIOR,
        RaceClass::TrollHunter => TROLL_HUNTER,
        RaceClass::TrollMage => TROLL_MAGE,
        RaceClass::TrollPriest => TROLL_PRIEST,
        RaceClass::TrollRogue => TROLL_ROGUE,
        RaceClass::TrollShaman => TROLL_SHAMAN,
        RaceClass::TrollWarrior => TROLL_WARRIOR,
        RaceClass::UndeadMage => UNDEAD_MAGE,
        RaceClass::UndeadPriest => UNDEAD_PRIEST,
        RaceClass::UndeadRogue => UNDEAD_ROGUE,
        RaceClass::UndeadWarlock => UNDEAD_WARLOCK,
        RaceClass::UndeadWarrior => UNDEAD_WARRIOR,
    }
}

// AUTOGENERATED_START
const HUMAN_WARRIOR: &[Action] = &[
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(83, 117, 128),
];
const HUMAN_PALADIN: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 20154, 0),
    Action::new(2, 635, 0),
    Action::new(10, 159, 128),
    Action::new(11, 2070, 128),
];
const HUMAN_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(11, 2070, 128),
];
const HUMAN_PRIEST: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 585, 0),
    Action::new(2, 2050, 0),
    Action::new(10, 159, 128),
    Action::new(11, 2070, 128),
];
const HUMAN_MAGE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 133, 0),
    Action::new(2, 168, 0),
    Action::new(10, 159, 128),
    Action::new(11, 2070, 128),
];
const HUMAN_WARLOCK: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 686, 0),
    Action::new(2, 687, 0),
    Action::new(10, 159, 128),
    Action::new(11, 4604, 128),
];
const ORC_WARRIOR: &[Action] = &[
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(74, 20572, 0),
    Action::new(83, 117, 128),
];
const ORC_HUNTER: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 2973, 0),
    Action::new(2, 75, 0),
    Action::new(4, 20572, 0),
    Action::new(10, 159, 128),
    Action::new(11, 117, 128),
];
const ORC_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(4, 20572, 0),
    Action::new(11, 117, 128),
];
const ORC_SHAMAN: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 403, 0),
    Action::new(2, 331, 0),
    Action::new(3, 20572, 0),
    Action::new(10, 159, 128),
    Action::new(11, 117, 128),
];
const ORC_WARLOCK: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 686, 0),
    Action::new(2, 687, 0),
    Action::new(3, 20572, 0),
    Action::new(10, 159, 128),
    Action::new(11, 117, 128),
];
const DWARF_WARRIOR: &[Action] = &[
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(74, 20594, 0),
    Action::new(75, 2481, 0),
    Action::new(83, 117, 128),
];
const DWARF_PALADIN: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 20154, 0),
    Action::new(2, 635, 0),
    Action::new(3, 20594, 0),
    Action::new(4, 2481, 0),
    Action::new(10, 159, 128),
    Action::new(11, 4540, 128),
];
const DWARF_HUNTER: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 2973, 0),
    Action::new(2, 75, 0),
    Action::new(3, 20594, 0),
    Action::new(4, 2481, 0),
    Action::new(10, 159, 128),
    Action::new(11, 117, 128),
];
const DWARF_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(4, 20594, 0),
    Action::new(5, 2481, 0),
    Action::new(11, 4540, 128),
];
const DWARF_PRIEST: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 585, 0),
    Action::new(2, 2050, 0),
    Action::new(3, 20594, 0),
    Action::new(4, 2481, 0),
    Action::new(10, 159, 128),
    Action::new(11, 4540, 128),
];
const NIGHT_ELF_WARRIOR: &[Action] = &[
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(74, 20580, 0),
    Action::new(83, 117, 128),
];
const NIGHT_ELF_HUNTER: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 2973, 0),
    Action::new(2, 75, 0),
    Action::new(3, 20580, 0),
    Action::new(10, 159, 128),
    Action::new(11, 117, 128),
];
const NIGHT_ELF_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(11, 4540, 128),
];
const NIGHT_ELF_PRIEST: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 585, 0),
    Action::new(2, 2050, 0),
    Action::new(3, 20580, 0),
    Action::new(10, 159, 128),
    Action::new(11, 2070, 128),
];
const NIGHT_ELF_DRUID: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 5176, 0),
    Action::new(2, 5185, 0),
    Action::new(3, 20580, 0),
    Action::new(10, 159, 128),
    Action::new(11, 4536, 128),
];
const UNDEAD_WARRIOR: &[Action] = &[
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(74, 20577, 0),
    Action::new(83, 4604, 128),
];
const UNDEAD_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(4, 20577, 0),
    Action::new(11, 4604, 128),
];
const UNDEAD_PRIEST: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 585, 0),
    Action::new(2, 2050, 0),
    Action::new(3, 20577, 0),
    Action::new(10, 159, 128),
    Action::new(11, 4604, 128),
];
const UNDEAD_MAGE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 133, 0),
    Action::new(2, 168, 0),
    Action::new(3, 20577, 0),
    Action::new(10, 159, 128),
    Action::new(11, 4604, 128),
];
const UNDEAD_WARLOCK: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 686, 0),
    Action::new(2, 687, 0),
    Action::new(3, 20577, 0),
    Action::new(10, 159, 128),
    Action::new(11, 4604, 128),
];
const TAUREN_WARRIOR: &[Action] = &[
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(74, 20549, 0),
    Action::new(83, 4540, 128),
];
const TAUREN_HUNTER: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 2973, 0),
    Action::new(2, 75, 0),
    Action::new(3, 20549, 0),
    Action::new(10, 159, 128),
    Action::new(11, 117, 128),
];
const TAUREN_SHAMAN: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 403, 0),
    Action::new(2, 331, 0),
    Action::new(3, 20549, 0),
    Action::new(10, 159, 128),
    Action::new(11, 4604, 128),
];
const TAUREN_DRUID: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 5176, 0),
    Action::new(2, 5185, 0),
    Action::new(3, 20549, 0),
    Action::new(10, 159, 128),
    Action::new(11, 4536, 128),
];
const GNOME_WARRIOR: &[Action] = &[
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(83, 117, 128),
];
const GNOME_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(11, 117, 128),
];
const GNOME_MAGE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 133, 0),
    Action::new(2, 168, 0),
    Action::new(10, 159, 128),
    Action::new(11, 4536, 128),
];
const GNOME_WARLOCK: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 686, 0),
    Action::new(2, 687, 0),
    Action::new(10, 159, 128),
    Action::new(11, 4604, 128),
];
const TROLL_WARRIOR: &[Action] = &[
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(74, 2764, 0),
    Action::new(75, 26296, 0),
    Action::new(83, 117, 128),
];
const TROLL_HUNTER: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 2973, 0),
    Action::new(2, 75, 0),
    Action::new(10, 159, 128),
    Action::new(11, 4604, 128),
];
const TROLL_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(4, 26972, 0),
    Action::new(11, 117, 128),
];
const TROLL_PRIEST: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 585, 0),
    Action::new(2, 2050, 0),
    Action::new(10, 159, 128),
    Action::new(11, 4540, 128),
];
const TROLL_SHAMAN: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 403, 0),
    Action::new(2, 331, 0),
    Action::new(10, 159, 128),
    Action::new(11, 117, 128),
];
const TROLL_MAGE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 133, 0),
    Action::new(2, 168, 0),
    Action::new(10, 159, 128),
    Action::new(11, 117, 128),
];
// AUTOGENERATED_END
