#[allow(clippy::too_many_arguments)]
pub(crate) mod constructors;
#[allow(non_upper_case_globals)]
mod data;

// AUTOGENERATED_START
pub use wow_world_base::tbc::{
    AuraMod,
    Reagent,
    Spell,
    SpellEffects,
    Totem,
    TotemCategory,
};

/// Looks up spells and returns if found.
///
/// Prefer using this over [`all_spells`] since this may incorporate optimizations for lookup speed in the future and is more resilient to changes.
pub const fn lookup_spell(id: u32) -> Option<&'static Spell> {
    let mut i = 0;
    const OBJ: &[Spell] = all_spells();

    while i < OBJ.len() {
        if OBJ[i].entry() == id {
            return Some(&OBJ[i]);
        }

        i += 1;
    }

    None
}

/// Returns all spells.
///
/// Prefer using [`lookup_spell`] since it may incorporate optimizations for lookup speed in the future.
pub const fn all_spells() -> &'static [Spell] {
    data::Z________DATA
}

// AUTOGENERATED_END
