#[allow(clippy::too_many_arguments)]
pub(crate) mod constructors;
#[allow(non_upper_case_globals)]
mod data;

// AUTOGENERATED_START
pub use wow_world_base::tbc::{
    AuraMod,
    Reagent,
    Spell,
    SpellEffects,
    Totem,
    TotemCategory,
};

pub fn lookup_spell(id: u32) -> Option<&'static Spell> {
    all_spells().iter().find(|a| a.entry() == id)
}

pub const fn all_spells() -> &'static [Spell] {
    data::DATA
}

// AUTOGENERATED_END
