pub(crate) mod constructors;
#[allow(non_upper_case_globals)]
mod data;

use crate::find_and_data;
// AUTOGENERATED_START
pub use wow_world_base::tbc::{
    Reagent,
    Spell,
    SpellEffect,
    Totem,
    TotemCategory,
};

// AUTOGENERATED_END

find_and_data!(data::DATA);
