pub(crate) mod constructors;
mod data;

use crate::find_and_data;
// AUTOGENERATED_START
pub use wow_world_base::wrath::{
    AllowedClass,
    AllowedRace,
    Area,
    BagFamily,
    Bonding,
    InventoryType,
    Item,
    ItemClassAndSubClass,
    ItemDamageType,
    ItemFlag,
    ItemFlag2,
    ItemQuality,
    ItemSet,
    ItemSocket,
    ItemStat,
    Language,
    Map,
    PageTextMaterial,
    PvpRank,
    SheatheType,
    Skill,
    SpellSchool,
    SpellTriggerType,
    Spells,
};

// AUTOGENERATED_END

find_and_data!(data::DATA);
