use wow_world_base::vanilla::{
    AllowedClass, AllowedRace, BagFamily, Bonding, Faction, Gold, InventoryType, 
    Item, ItemClassAndSubClass, ItemDamageType, ItemFlag, ItemQuality, ItemSet, 
    Language, PageTextMaterial, PvpRank, SheatheType, Skill, Spells,
};

const EMPTY_ITEMDAMAGETYPE:&[ItemDamageType]=&[];
const EMPTY_SPELLS:&[Spells]=&[];
pub const fn n(
    entry: u16,
    class_and_sub_class: ItemClassAndSubClass,
    name: &'static str,
    display_id: u16,
    quality: ItemQuality,
    flags: u32,
    buy_count: i16,
    buy_price: u32,
    sell_price: u32,
    inventory_type: InventoryType,
    allowed_class: u32,
    allowed_race: u32,
    item_level: i8,
    required_level: i8,
    required_skill: Skill,
    required_skill_rank: i16,
    required_honor_rank: PvpRank,
    required_faction: Faction,
    required_reputation_rank: i8,
    max_count: i16,
    stackable: i16,
    container_slots: i8,
    agility: i8,
    strength: i8,
    stamina: i8,
    intellect: i16,
    spirit: i8,
    armor: i16,
    fire_res: i16,
    nature_res: i16,
    frost_res: i16,
    shadow_res: i16,
    delay: i16,
    ammo_type: i8,
    ranged_mod_range: f32,
    bonding: Bonding,
    description: &'static str,
    page_text: i16,
    language: Language,
    page_text_material: PageTextMaterial,
    start_quest: i16,
    material: i8,
    sheathe_type: SheatheType,
    random_property: i16,
    block: i8,
    item_set: ItemSet,
    max_durability: i16,
    bag_family: BagFamily,
    disenchant_id: i8,
    food_type: i8,
    extra_flags: i8,
    damages: &'static [ItemDamageType],
    spells: &'static [Spells],
) -> Item {
    Item::new(
        entry,
        class_and_sub_class,
        name,
        display_id,
        quality,
        ItemFlag::new(flags),
        buy_count,
        Gold::new(buy_price),
        Gold::new(sell_price),
        inventory_type,
        AllowedClass::new(allowed_class),
        AllowedRace::new(allowed_race),
        item_level,
        required_level,
        required_skill,
        required_skill_rank,
        required_honor_rank,
        required_faction,
        required_reputation_rank,
        max_count,
        stackable,
        container_slots,
        agility,
        strength,
        stamina,
        intellect,
        spirit,
        armor,
        fire_res,
        nature_res,
        frost_res,
        shadow_res,
        delay,
        ammo_type,
        ranged_mod_range,
        bonding,
        description,
        page_text,
        language,
        page_text_material,
        start_quest,
        material,
        sheathe_type,
        random_property,
        block,
        item_set,
        max_durability,
        bag_family,
        disenchant_id,
        food_type,
        extra_flags,
        damages,
        spells,
    )
}
pub const fn na(
    entry: u16,
    class_and_sub_class: ItemClassAndSubClass,
    name: &'static str,
    display_id: u16,
    quality: ItemQuality,
    flags: u32,
    buy_count: i16,
    buy_price: u32,
    sell_price: u32,
    inventory_type: InventoryType,
    allowed_class: u32,
    allowed_race: u32,
    item_level: i8,
    required_level: i8,
    required_skill: Skill,
    required_skill_rank: i16,
    required_honor_rank: PvpRank,
    required_faction: Faction,
    required_reputation_rank: i8,
    max_count: i16,
    stackable: i16,
    container_slots: i8,
    agility: i8,
    strength: i8,
    stamina: i8,
    intellect: i16,
    spirit: i8,
    armor: i16,
    fire_res: i16,
    nature_res: i16,
    frost_res: i16,
    shadow_res: i16,
    delay: i16,
    ammo_type: i8,
    ranged_mod_range: f32,
    bonding: Bonding,
    description: &'static str,
    page_text: i16,
    language: Language,
    page_text_material: PageTextMaterial,
    start_quest: i16,
    material: i8,
    sheathe_type: SheatheType,
    random_property: i16,
    block: i8,
    item_set: ItemSet,
    max_durability: i16,
    bag_family: BagFamily,
    disenchant_id: i8,
    food_type: i8,
    extra_flags: i8,
    spells: &'static [Spells],
) -> Item {
    Item::new(
        entry,
        class_and_sub_class,
        name,
        display_id,
        quality,
        ItemFlag::new(flags),
        buy_count,
        Gold::new(buy_price),
        Gold::new(sell_price),
        inventory_type,
        AllowedClass::new(allowed_class),
        AllowedRace::new(allowed_race),
        item_level,
        required_level,
        required_skill,
        required_skill_rank,
        required_honor_rank,
        required_faction,
        required_reputation_rank,
        max_count,
        stackable,
        container_slots,
        agility,
        strength,
        stamina,
        intellect,
        spirit,
        armor,
        fire_res,
        nature_res,
        frost_res,
        shadow_res,
        delay,
        ammo_type,
        ranged_mod_range,
        bonding,
        description,
        page_text,
        language,
        page_text_material,
        start_quest,
        material,
        sheathe_type,
        random_property,
        block,
        item_set,
        max_durability,
        bag_family,
        disenchant_id,
        food_type,
        extra_flags,
        EMPTY_ITEMDAMAGETYPE,
        spells,
    )
}
pub const fn nab(
    entry: u16,
    class_and_sub_class: ItemClassAndSubClass,
    name: &'static str,
    display_id: u16,
    quality: ItemQuality,
    flags: u32,
    buy_count: i16,
    buy_price: u32,
    sell_price: u32,
    inventory_type: InventoryType,
    allowed_class: u32,
    allowed_race: u32,
    item_level: i8,
    required_level: i8,
    required_skill: Skill,
    required_skill_rank: i16,
    required_honor_rank: PvpRank,
    required_faction: Faction,
    required_reputation_rank: i8,
    max_count: i16,
    stackable: i16,
    container_slots: i8,
    agility: i8,
    strength: i8,
    stamina: i8,
    intellect: i16,
    spirit: i8,
    armor: i16,
    fire_res: i16,
    nature_res: i16,
    frost_res: i16,
    shadow_res: i16,
    delay: i16,
    ammo_type: i8,
    ranged_mod_range: f32,
    bonding: Bonding,
    description: &'static str,
    page_text: i16,
    language: Language,
    page_text_material: PageTextMaterial,
    start_quest: i16,
    material: i8,
    sheathe_type: SheatheType,
    random_property: i16,
    block: i8,
    item_set: ItemSet,
    max_durability: i16,
    bag_family: BagFamily,
    disenchant_id: i8,
    food_type: i8,
    extra_flags: i8,
) -> Item {
    Item::new(
        entry,
        class_and_sub_class,
        name,
        display_id,
        quality,
        ItemFlag::new(flags),
        buy_count,
        Gold::new(buy_price),
        Gold::new(sell_price),
        inventory_type,
        AllowedClass::new(allowed_class),
        AllowedRace::new(allowed_race),
        item_level,
        required_level,
        required_skill,
        required_skill_rank,
        required_honor_rank,
        required_faction,
        required_reputation_rank,
        max_count,
        stackable,
        container_slots,
        agility,
        strength,
        stamina,
        intellect,
        spirit,
        armor,
        fire_res,
        nature_res,
        frost_res,
        shadow_res,
        delay,
        ammo_type,
        ranged_mod_range,
        bonding,
        description,
        page_text,
        language,
        page_text_material,
        start_quest,
        material,
        sheathe_type,
        random_property,
        block,
        item_set,
        max_durability,
        bag_family,
        disenchant_id,
        food_type,
        extra_flags,
        EMPTY_ITEMDAMAGETYPE,
        EMPTY_SPELLS,
    )
}
pub const fn nb(
    entry: u16,
    class_and_sub_class: ItemClassAndSubClass,
    name: &'static str,
    display_id: u16,
    quality: ItemQuality,
    flags: u32,
    buy_count: i16,
    buy_price: u32,
    sell_price: u32,
    inventory_type: InventoryType,
    allowed_class: u32,
    allowed_race: u32,
    item_level: i8,
    required_level: i8,
    required_skill: Skill,
    required_skill_rank: i16,
    required_honor_rank: PvpRank,
    required_faction: Faction,
    required_reputation_rank: i8,
    max_count: i16,
    stackable: i16,
    container_slots: i8,
    agility: i8,
    strength: i8,
    stamina: i8,
    intellect: i16,
    spirit: i8,
    armor: i16,
    fire_res: i16,
    nature_res: i16,
    frost_res: i16,
    shadow_res: i16,
    delay: i16,
    ammo_type: i8,
    ranged_mod_range: f32,
    bonding: Bonding,
    description: &'static str,
    page_text: i16,
    language: Language,
    page_text_material: PageTextMaterial,
    start_quest: i16,
    material: i8,
    sheathe_type: SheatheType,
    random_property: i16,
    block: i8,
    item_set: ItemSet,
    max_durability: i16,
    bag_family: BagFamily,
    disenchant_id: i8,
    food_type: i8,
    extra_flags: i8,
    damages: &'static [ItemDamageType],
) -> Item {
    Item::new(
        entry,
        class_and_sub_class,
        name,
        display_id,
        quality,
        ItemFlag::new(flags),
        buy_count,
        Gold::new(buy_price),
        Gold::new(sell_price),
        inventory_type,
        AllowedClass::new(allowed_class),
        AllowedRace::new(allowed_race),
        item_level,
        required_level,
        required_skill,
        required_skill_rank,
        required_honor_rank,
        required_faction,
        required_reputation_rank,
        max_count,
        stackable,
        container_slots,
        agility,
        strength,
        stamina,
        intellect,
        spirit,
        armor,
        fire_res,
        nature_res,
        frost_res,
        shadow_res,
        delay,
        ammo_type,
        ranged_mod_range,
        bonding,
        description,
        page_text,
        language,
        page_text_material,
        start_quest,
        material,
        sheathe_type,
        random_property,
        block,
        item_set,
        max_durability,
        bag_family,
        disenchant_id,
        food_type,
        extra_flags,
        damages,
        EMPTY_SPELLS,
    )
}
