#[allow(clippy::too_many_arguments)]
mod constructors;
#[allow(non_upper_case_globals)]
mod data;

// AUTOGENERATED_START
pub use wow_world_base::vanilla::{
    AllowedClass,
    AllowedRace,
    Area,
    BagFamily,
    Bonding,
    Faction,
    Gold,
    InventoryType,
    Item,
    ItemClassAndSubClass,
    ItemDamageType,
    ItemFlag,
    ItemQuality,
    ItemSet,
    Language,
    Map,
    PageTextMaterial,
    PvpRank,
    SheatheType,
    Skill,
    SpellSchool,
    SpellTriggerType,
    Spells,
};

// AUTOGENERATED_END

pub fn lookup_item(id: u32) -> Option<&'static Item> {
    all_items().iter().find(|a| a.entry() == id)
}

pub const fn all_items() -> &'static [Item] {
    data::DATA
}
