#[allow(clippy::too_many_arguments)]
mod constructors;
#[allow(non_upper_case_globals)]
mod data;

// AUTOGENERATED_START
pub use wow_world_base::vanilla::{
    AllowedClass,
    AllowedRace,
    Area,
    BagFamily,
    Bonding,
    Faction,
    Gold,
    InventoryType,
    Item,
    ItemClassAndSubClass,
    ItemDamageType,
    ItemFlag,
    ItemQuality,
    ItemSet,
    Language,
    Map,
    PageTextMaterial,
    PvpRank,
    SheatheType,
    Skill,
    SpellSchool,
    SpellTriggerType,
    Spells,
};

/// Looks up items and returns if found.
///
/// Prefer using this over [`all_items`] since this utilizes a lookup array for very fast lookup.
pub const fn lookup_item(id: u32) -> Option<&'static Item> {
    if id < 25 || id > 25818 {
        return None;
    }

    const OBJ: &[Item] = all_items();

    let index = data::Z________LOOKUP[id as usize];
    if index == u16::MAX {
        None
    } else {
        Some(&OBJ[index as usize])
    }
}

/// Returns all items.
///
/// Prefer using [`lookup_item`] since it incorporates optimizations for lookup speed.
pub const fn all_items() -> &'static [Item] {
    data::Z________DATA
}

// AUTOGENERATED_END
