pub(crate) mod constructors;
mod data;

use crate::find_and_data;
// AUTOGENERATED_START
pub use wow_world_base::wrath::{
    Reagent,
    Spell,
    SpellEffect,
    Totem,
    TotemCategory,
};

// AUTOGENERATED_END

find_and_data!(data::DATA);
