use crate::shared::exp_required_to_level_up;

pub const MAX_LEVEL: u8 = 70;

// AUTOGENERATED_START
const EXP_REQUIRED_FOR_LEVEL: [i32; 69] = [
    400, // Required to ding from level 1
    900, // Required to ding from level 2
    1400, // Required to ding from level 3
    2100, // Required to ding from level 4
    2800, // Required to ding from level 5
    3600, // Required to ding from level 6
    4500, // Required to ding from level 7
    5400, // Required to ding from level 8
    6500, // Required to ding from level 9
    7600, // Required to ding from level 10
    8700, // Required to ding from level 11
    9800, // Required to ding from level 12
    11000, // Required to ding from level 13
    12300, // Required to ding from level 14
    13600, // Required to ding from level 15
    15000, // Required to ding from level 16
    16400, // Required to ding from level 17
    17800, // Required to ding from level 18
    19300, // Required to ding from level 19
    20800, // Required to ding from level 20
    22400, // Required to ding from level 21
    24000, // Required to ding from level 22
    25500, // Required to ding from level 23
    27200, // Required to ding from level 24
    28900, // Required to ding from level 25
    30500, // Required to ding from level 26
    32200, // Required to ding from level 27
    33900, // Required to ding from level 28
    36300, // Required to ding from level 29
    38800, // Required to ding from level 30
    41600, // Required to ding from level 31
    44600, // Required to ding from level 32
    48000, // Required to ding from level 33
    51400, // Required to ding from level 34
    55000, // Required to ding from level 35
    58700, // Required to ding from level 36
    62400, // Required to ding from level 37
    66200, // Required to ding from level 38
    70200, // Required to ding from level 39
    74300, // Required to ding from level 40
    78500, // Required to ding from level 41
    82800, // Required to ding from level 42
    87100, // Required to ding from level 43
    91600, // Required to ding from level 44
    96300, // Required to ding from level 45
    101000, // Required to ding from level 46
    105800, // Required to ding from level 47
    110700, // Required to ding from level 48
    115700, // Required to ding from level 49
    120900, // Required to ding from level 50
    126100, // Required to ding from level 51
    131500, // Required to ding from level 52
    137000, // Required to ding from level 53
    142500, // Required to ding from level 54
    148200, // Required to ding from level 55
    154000, // Required to ding from level 56
    159900, // Required to ding from level 57
    165800, // Required to ding from level 58
    172000, // Required to ding from level 59
    494000, // Required to ding from level 60
    574700, // Required to ding from level 61
    614400, // Required to ding from level 62
    650300, // Required to ding from level 63
    682300, // Required to ding from level 64
    710200, // Required to ding from level 65
    734100, // Required to ding from level 66
    753700, // Required to ding from level 67
    768900, // Required to ding from level 68
    779700, // Required to ding from level 69
];
// AUTOGENERATED_END

exp_required_to_level_up!(MAX_LEVEL);
