pub(crate) mod constructors;
mod data;

use crate::find_and_data;
// AUTOGENERATED_START
pub use wow_world_base::tbc::{
    AllowedClass,
    AllowedRace,
    Area,
    Bonding,
    InventoryType,
    Item,
    ItemClassAndSubClass,
    ItemDamageType,
    ItemQuality,
    ItemSocket,
    ItemStat,
    Map,
    Skill,
    SpellSchool,
    SpellTriggerType,
    Spells,
};

// AUTOGENERATED_END

find_and_data!(data::DATA);
