#[allow(clippy::too_many_arguments)]
mod constructors;
#[allow(non_upper_case_globals)]
mod data;

// AUTOGENERATED_START
pub use wow_world_base::vanilla::{
    Attributes,
    AttributesEx1,
    AttributesEx2,
    AttributesEx3,
    AttributesEx4,
    AuraMod,
    Reagent,
    Spell,
    SpellEffects,
    Totem,
};

/// Looks up spells and returns if found.
///
/// Prefer using this over [`all_spells`] since this utilizes a lookup array for very fast lookup.
pub const fn lookup_spell(id: u32) -> Option<&'static Spell> {
    if id < 1 || id > 33392 {
        return None;
    }

    let index = data::Z________LOOKUP[(id - 1) as usize];
    if index == u16::MAX || index as usize > (all_spells().len() - 1) {
        None
    } else {
        Some(&all_spells()[index as usize])
    }
}

/// Returns all spells.
///
/// Prefer using [`lookup_spell`] since it incorporates optimizations for lookup speed.
pub const fn all_spells() -> &'static [Spell] {
    data::Z________DATA
}

// AUTOGENERATED_END
