use crate::shared::Action;
use wow_world_base::wrath::RaceClass;

pub const fn starter_actions(combo: RaceClass) -> &'static [Action] {
    match combo {
        RaceClass::DwarfHunter => DWARF_HUNTER,
        RaceClass::DwarfPaladin => DWARF_PALADIN,
        RaceClass::DwarfPriest => DWARF_PRIEST,
        RaceClass::DwarfRogue => DWARF_ROGUE,
        RaceClass::DwarfWarrior => DWARF_WARRIOR,
        RaceClass::GnomeMage => GNOME_MAGE,
        RaceClass::GnomeRogue => GNOME_ROGUE,
        RaceClass::GnomeWarlock => GNOME_WARLOCK,
        RaceClass::GnomeWarrior => GNOME_WARRIOR,
        RaceClass::HumanMage => HUMAN_MAGE,
        RaceClass::HumanPaladin => HUMAN_PALADIN,
        RaceClass::HumanPriest => HUMAN_PRIEST,
        RaceClass::HumanRogue => HUMAN_ROGUE,
        RaceClass::HumanWarlock => HUMAN_WARLOCK,
        RaceClass::HumanWarrior => HUMAN_WARRIOR,
        RaceClass::NightElfDruid => NIGHT_ELF_DRUID,
        RaceClass::NightElfHunter => NIGHT_ELF_HUNTER,
        RaceClass::NightElfPriest => NIGHT_ELF_PRIEST,
        RaceClass::NightElfRogue => NIGHT_ELF_ROGUE,
        RaceClass::NightElfWarrior => NIGHT_ELF_WARRIOR,
        RaceClass::OrcHunter => ORC_HUNTER,
        RaceClass::OrcRogue => ORC_ROGUE,
        RaceClass::OrcShaman => ORC_SHAMAN,
        RaceClass::OrcWarlock => ORC_WARLOCK,
        RaceClass::OrcWarrior => ORC_WARRIOR,
        RaceClass::TaurenDruid => TAUREN_DRUID,
        RaceClass::TaurenHunter => TAUREN_HUNTER,
        RaceClass::TaurenShaman => TAUREN_SHAMAN,
        RaceClass::TaurenWarrior => TAUREN_WARRIOR,
        RaceClass::TrollHunter => TROLL_HUNTER,
        RaceClass::TrollMage => TROLL_MAGE,
        RaceClass::TrollPriest => TROLL_PRIEST,
        RaceClass::TrollRogue => TROLL_ROGUE,
        RaceClass::TrollShaman => TROLL_SHAMAN,
        RaceClass::TrollWarrior => TROLL_WARRIOR,
        RaceClass::UndeadMage => UNDEAD_MAGE,
        RaceClass::UndeadPriest => UNDEAD_PRIEST,
        RaceClass::UndeadRogue => UNDEAD_ROGUE,
        RaceClass::UndeadWarlock => UNDEAD_WARLOCK,
        RaceClass::UndeadWarrior => UNDEAD_WARRIOR,
        RaceClass::DraeneiWarrior => DRAENEI_WARRIOR,
        RaceClass::DraeneiPaladin => DRAENEI_PALADIN,
        RaceClass::DraeneiHunter => DRAENEI_HUNTER,
        RaceClass::DraeneiPriest => DRAENEI_PRIEST,
        RaceClass::DraeneiShaman => DRAENEI_SHAMAN,
        RaceClass::DraeneiMage => DRAENEI_MAGE,
        RaceClass::BloodElfPaladin => BLOOD_ELF_PALADIN,
        RaceClass::BloodElfHunter => BLOOD_ELF_HUNTER,
        RaceClass::BloodElfRogue => BLOOD_ELF_ROGUE,
        RaceClass::BloodElfPriest => BLOOD_ELF_PRIEST,
        RaceClass::BloodElfMage => BLOOD_ELF_MAGE,
        RaceClass::BloodElfWarlock => BLOOD_ELF_WARLOCK,
        RaceClass::HumanDeathKnight => HUMAN_DEATH_KNIGHT,
        RaceClass::OrcDeathKnight => ORC_DEATH_KNIGHT,
        RaceClass::DwarfDeathKnight => DWARF_DEATH_KNIGHT,
        RaceClass::NightElfDeathKnight => NIGHT_ELF_DEATH_KNIGHT,
        RaceClass::UndeadDeathKnight => UNDEAD_DEATH_KNIGHT,
        RaceClass::TaurenDeathKnight => TAUREN_DEATH_KNIGHT,
        RaceClass::GnomeDeathKnight => GNOME_DEATH_KNIGHT,
        RaceClass::TrollDeathKnight => TROLL_DEATH_KNIGHT,
        RaceClass::BloodElfDeathKnight => BLOOD_ELF_DEATH_KNIGHT,
        RaceClass::DraeneiDeathKnight => DRAENEI_DEATH_KNIGHT,
    }
}

// AUTOGENERATED_START
const HUMAN_WARRIOR: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 78, 0),
    Action::new(9, 59752, 0),
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(82, 59752, 0),
    Action::new(84, 6603, 0),
    Action::new(96, 6603, 0),
    Action::new(108, 6603, 0),
];
const HUMAN_PALADIN: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 21084, 0),
    Action::new(2, 635, 0),
    Action::new(9, 59752, 0),
];
const HUMAN_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(10, 59752, 0),
];
const HUMAN_PRIEST: &[Action] = &[
    Action::new(0, 585, 0),
    Action::new(1, 2050, 0),
    Action::new(9, 59752, 0),
];
const HUMAN_DEATH_KNIGHT: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 49576, 0),
    Action::new(2, 45477, 0),
    Action::new(3, 45462, 0),
    Action::new(4, 45902, 0),
    Action::new(5, 47541, 0),
    Action::new(11, 59752, 0),
];
const HUMAN_MAGE: &[Action] = &[
    Action::new(0, 133, 0),
    Action::new(1, 168, 0),
    Action::new(9, 59752, 0),
];
const HUMAN_WARLOCK: &[Action] = &[
    Action::new(0, 686, 0),
    Action::new(1, 687, 0),
    Action::new(9, 59752, 0),
    Action::new(11, 4604, 128),
];
const ORC_WARRIOR: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 78, 0),
    Action::new(2, 20572, 0),
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(74, 20572, 0),
    Action::new(84, 6603, 0),
    Action::new(96, 6603, 0),
    Action::new(108, 6603, 0),
];
const ORC_HUNTER: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 2973, 0),
    Action::new(2, 75, 0),
    Action::new(9, 20572, 0),
];
const ORC_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(4, 20572, 0),
];
const ORC_DEATH_KNIGHT: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 49576, 0),
    Action::new(2, 45477, 0),
    Action::new(3, 45462, 0),
    Action::new(4, 45902, 0),
    Action::new(5, 47541, 0),
    Action::new(10, 20572, 0),
];
const ORC_SHAMAN: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 403, 0),
    Action::new(2, 331, 0),
    Action::new(3, 33697, 0),
];
const ORC_WARLOCK: &[Action] = &[
    Action::new(0, 686, 0),
    Action::new(1, 687, 0),
    Action::new(2, 33702, 0),
];
const DWARF_WARRIOR: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 78, 0),
    Action::new(2, 20594, 0),
    Action::new(3, 2481, 0),
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(74, 20594, 0),
    Action::new(75, 2481, 0),
    Action::new(84, 6603, 0),
    Action::new(96, 6603, 0),
    Action::new(108, 6603, 0),
];
const DWARF_PALADIN: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 21084, 0),
    Action::new(2, 635, 0),
    Action::new(3, 20594, 0),
    Action::new(4, 2481, 0),
];
const DWARF_HUNTER: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 2973, 0),
    Action::new(2, 75, 0),
    Action::new(3, 20594, 0),
    Action::new(4, 2481, 0),
    Action::new(75, 20594, 0),
    Action::new(76, 2481, 0),
];
const DWARF_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(4, 20594, 0),
    Action::new(5, 2481, 0),
];
const DWARF_PRIEST: &[Action] = &[
    Action::new(0, 585, 0),
    Action::new(1, 2050, 0),
    Action::new(2, 20594, 0),
    Action::new(3, 2481, 0),
];
const DWARF_DEATH_KNIGHT: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 49576, 0),
    Action::new(2, 45477, 0),
    Action::new(3, 45462, 0),
    Action::new(4, 45902, 0),
    Action::new(5, 47541, 0),
    Action::new(10, 2481, 0),
];
const NIGHT_ELF_WARRIOR: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 78, 0),
    Action::new(2, 58984, 0),
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(74, 58984, 0),
    Action::new(84, 6603, 0),
    Action::new(96, 6603, 0),
    Action::new(108, 6603, 0),
];
const NIGHT_ELF_HUNTER: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 2973, 0),
    Action::new(2, 75, 0),
    Action::new(3, 58984, 0),
    Action::new(81, 58984, 0),
];
const NIGHT_ELF_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(4, 58984, 0),
    Action::new(82, 58984, 0),
];
const NIGHT_ELF_PRIEST: &[Action] = &[
    Action::new(0, 585, 0),
    Action::new(1, 2050, 0),
    Action::new(2, 58984, 0),
    Action::new(81, 58984, 0),
];
const NIGHT_ELF_DEATH_KNIGHT: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 49576, 0),
    Action::new(2, 45477, 0),
    Action::new(3, 45462, 0),
    Action::new(4, 45902, 0),
    Action::new(5, 47541, 0),
    Action::new(10, 58984, 0),
    Action::new(83, 58984, 0),
];
const NIGHT_ELF_DRUID: &[Action] = &[
    Action::new(0, 5176, 0),
    Action::new(1, 5185, 0),
    Action::new(2, 58984, 0),
    Action::new(72, 6603, 0),
    Action::new(74, 58984, 0),
    Action::new(84, 6603, 0),
    Action::new(96, 6603, 0),
    Action::new(108, 6603, 0),
];
const UNDEAD_WARRIOR: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 78, 0),
    Action::new(2, 20577, 0),
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(74, 20577, 0),
    Action::new(83, 4604, 128),
    Action::new(84, 6603, 0),
    Action::new(96, 6603, 0),
    Action::new(108, 6603, 0),
];
const UNDEAD_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(4, 20577, 0),
    Action::new(11, 4604, 128),
];
const UNDEAD_PRIEST: &[Action] = &[
    Action::new(0, 585, 0),
    Action::new(1, 2050, 0),
    Action::new(2, 20577, 0),
];
const UNDEAD_DEATH_KNIGHT: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 49576, 0),
    Action::new(2, 45477, 0),
    Action::new(3, 45462, 0),
    Action::new(4, 45902, 0),
    Action::new(5, 47541, 0),
    Action::new(10, 20577, 0),
];
const UNDEAD_MAGE: &[Action] = &[
    Action::new(0, 133, 0),
    Action::new(1, 168, 0),
    Action::new(2, 20577, 0),
];
const UNDEAD_WARLOCK: &[Action] = &[
    Action::new(0, 686, 0),
    Action::new(1, 687, 0),
    Action::new(2, 20577, 0),
];
const TAUREN_WARRIOR: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 78, 0),
    Action::new(2, 20549, 0),
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(74, 20549, 0),
    Action::new(84, 6603, 0),
    Action::new(96, 6603, 0),
    Action::new(108, 6603, 0),
];
const TAUREN_HUNTER: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 2973, 0),
    Action::new(2, 75, 0),
    Action::new(3, 20549, 0),
    Action::new(75, 20549, 0),
];
const TAUREN_DEATH_KNIGHT: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 49576, 0),
    Action::new(2, 45477, 0),
    Action::new(3, 45462, 0),
    Action::new(4, 45902, 0),
    Action::new(5, 47541, 0),
    Action::new(10, 20549, 0),
    Action::new(75, 20549, 0),
];
const TAUREN_SHAMAN: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 403, 0),
    Action::new(2, 331, 0),
    Action::new(3, 20549, 0),
    Action::new(11, 4604, 128),
    Action::new(75, 20549, 0),
];
const TAUREN_DRUID: &[Action] = &[
    Action::new(0, 5176, 0),
    Action::new(1, 5185, 0),
    Action::new(2, 20549, 0),
    Action::new(72, 6603, 0),
    Action::new(75, 20549, 0),
    Action::new(84, 6603, 0),
    Action::new(96, 6603, 0),
    Action::new(108, 6603, 0),
];
const GNOME_WARRIOR: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 78, 0),
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(84, 6603, 0),
    Action::new(96, 6603, 0),
    Action::new(108, 6603, 0),
];
const GNOME_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
];
const GNOME_DEATH_KNIGHT: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 49576, 0),
    Action::new(2, 45477, 0),
    Action::new(3, 45462, 0),
    Action::new(4, 45902, 0),
    Action::new(5, 47541, 0),
    Action::new(10, 20589, 0),
    Action::new(11, 41751, 128),
    Action::new(72, 6603, 0),
    Action::new(83, 41751, 128),
    Action::new(84, 6603, 0),
    Action::new(96, 6603, 0),
    Action::new(108, 6603, 0),
];
const GNOME_MAGE: &[Action] = &[Action::new(0, 133, 0), Action::new(1, 168, 0)];
const GNOME_WARLOCK: &[Action] = &[Action::new(0, 686, 0), Action::new(1, 687, 0)];
const TROLL_WARRIOR: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 78, 0),
    Action::new(2, 26297, 0),
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(74, 2764, 0),
    Action::new(75, 26297, 0),
    Action::new(84, 6603, 0),
    Action::new(96, 6603, 0),
    Action::new(108, 6603, 0),
];
const TROLL_HUNTER: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 2973, 0),
    Action::new(2, 75, 0),
    Action::new(3, 26297, 0),
    Action::new(11, 4604, 128),
];
const TROLL_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(4, 26297, 0),
    Action::new(76, 26297, 0),
];
const TROLL_PRIEST: &[Action] = &[
    Action::new(0, 585, 0),
    Action::new(1, 2050, 0),
    Action::new(2, 26297, 0),
];
const TROLL_DEATH_KNIGHT: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 49576, 0),
    Action::new(2, 45477, 0),
    Action::new(3, 45462, 0),
    Action::new(4, 45902, 0),
    Action::new(5, 47541, 0),
    Action::new(10, 26297, 0),
];
const TROLL_SHAMAN: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 403, 0),
    Action::new(2, 331, 0),
    Action::new(3, 26297, 0),
];
const TROLL_MAGE: &[Action] = &[
    Action::new(0, 133, 0),
    Action::new(1, 168, 0),
    Action::new(2, 26297, 0),
];
const BLOOD_ELF_PALADIN: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 21084, 0),
    Action::new(2, 635, 0),
    Action::new(3, 28730, 0),
];
const BLOOD_ELF_HUNTER: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 2973, 0),
    Action::new(2, 75, 0),
    Action::new(3, 28730, 0),
];
const BLOOD_ELF_ROGUE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 1752, 0),
    Action::new(2, 2098, 0),
    Action::new(3, 2764, 0),
    Action::new(4, 25046, 0),
];
const BLOOD_ELF_PRIEST: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 585, 0),
    Action::new(2, 2050, 0),
    Action::new(3, 28730, 0),
];
const BLOOD_ELF_DEATH_KNIGHT: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 49576, 0),
    Action::new(2, 45477, 0),
    Action::new(3, 45462, 0),
    Action::new(4, 45902, 0),
    Action::new(5, 47541, 0),
    Action::new(6, 50613, 0),
];
const BLOOD_ELF_MAGE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 133, 0),
    Action::new(2, 168, 0),
    Action::new(3, 28730, 0),
];
const BLOOD_ELF_WARLOCK: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 686, 0),
    Action::new(2, 687, 0),
    Action::new(3, 28730, 0),
];
const DRAENEI_WARRIOR: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(72, 6603, 0),
    Action::new(73, 78, 0),
    Action::new(74, 28880, 0),
    Action::new(84, 6603, 0),
    Action::new(96, 6603, 0),
    Action::new(108, 6603, 0),
];
const DRAENEI_PALADIN: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 21084, 0),
    Action::new(2, 635, 0),
    Action::new(3, 59542, 0),
];
const DRAENEI_HUNTER: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 2973, 0),
    Action::new(2, 75, 0),
    Action::new(3, 59543, 0),
    Action::new(72, 6603, 0),
    Action::new(73, 2973, 0),
    Action::new(74, 75, 0),
];
const DRAENEI_PRIEST: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 585, 0),
    Action::new(2, 2050, 0),
    Action::new(3, 59544, 0),
];
const DRAENEI_DEATH_KNIGHT: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 49576, 0),
    Action::new(2, 45477, 0),
    Action::new(3, 45462, 0),
    Action::new(4, 45902, 0),
    Action::new(5, 47541, 0),
    Action::new(10, 59545, 0),
    Action::new(11, 41751, 128),
];
const DRAENEI_SHAMAN: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 403, 0),
    Action::new(2, 331, 0),
    Action::new(3, 59547, 0),
];
const DRAENEI_MAGE: &[Action] = &[
    Action::new(0, 6603, 0),
    Action::new(1, 133, 0),
    Action::new(2, 168, 0),
    Action::new(3, 59548, 0),
];
// AUTOGENERATED_END
