use wow_world_base::wrath::RaceClass;

pub const fn starter_skills(combo: RaceClass) -> &'static [u32] {
    match combo {
        RaceClass::DwarfHunter => DWARF_HUNTER,
        RaceClass::DwarfPaladin => DWARF_PALADIN,
        RaceClass::DwarfPriest => DWARF_PRIEST,
        RaceClass::DwarfRogue => DWARF_ROGUE,
        RaceClass::DwarfWarrior => DWARF_WARRIOR,
        RaceClass::GnomeMage => GNOME_MAGE,
        RaceClass::GnomeRogue => GNOME_ROGUE,
        RaceClass::GnomeWarlock => GNOME_WARLOCK,
        RaceClass::GnomeWarrior => GNOME_WARRIOR,
        RaceClass::HumanMage => HUMAN_MAGE,
        RaceClass::HumanPaladin => HUMAN_PALADIN,
        RaceClass::HumanPriest => HUMAN_PRIEST,
        RaceClass::HumanRogue => HUMAN_ROGUE,
        RaceClass::HumanWarlock => HUMAN_WARLOCK,
        RaceClass::HumanWarrior => HUMAN_WARRIOR,
        RaceClass::NightElfDruid => NIGHT_ELF_DRUID,
        RaceClass::NightElfHunter => NIGHT_ELF_HUNTER,
        RaceClass::NightElfPriest => NIGHT_ELF_PRIEST,
        RaceClass::NightElfRogue => NIGHT_ELF_ROGUE,
        RaceClass::NightElfWarrior => NIGHT_ELF_WARRIOR,
        RaceClass::OrcHunter => ORC_HUNTER,
        RaceClass::OrcRogue => ORC_ROGUE,
        RaceClass::OrcShaman => ORC_SHAMAN,
        RaceClass::OrcWarlock => ORC_WARLOCK,
        RaceClass::OrcWarrior => ORC_WARRIOR,
        RaceClass::TaurenDruid => TAUREN_DRUID,
        RaceClass::TaurenHunter => TAUREN_HUNTER,
        RaceClass::TaurenShaman => TAUREN_SHAMAN,
        RaceClass::TaurenWarrior => TAUREN_WARRIOR,
        RaceClass::TrollHunter => TROLL_HUNTER,
        RaceClass::TrollMage => TROLL_MAGE,
        RaceClass::TrollPriest => TROLL_PRIEST,
        RaceClass::TrollRogue => TROLL_ROGUE,
        RaceClass::TrollShaman => TROLL_SHAMAN,
        RaceClass::TrollWarrior => TROLL_WARRIOR,
        RaceClass::UndeadMage => UNDEAD_MAGE,
        RaceClass::UndeadPriest => UNDEAD_PRIEST,
        RaceClass::UndeadRogue => UNDEAD_ROGUE,
        RaceClass::UndeadWarlock => UNDEAD_WARLOCK,
        RaceClass::UndeadWarrior => UNDEAD_WARRIOR,
        RaceClass::DraeneiWarrior => DRAENEI_WARRIOR,
        RaceClass::DraeneiPaladin => DRAENEI_PALADIN,
        RaceClass::DraeneiHunter => DRAENEI_HUNTER,
        RaceClass::DraeneiPriest => DRAENEI_PRIEST,
        RaceClass::DraeneiShaman => DRAENEI_SHAMAN,
        RaceClass::DraeneiMage => DRAENEI_MAGE,
        RaceClass::BloodElfPaladin => BLOOD_ELF_PALADIN,
        RaceClass::BloodElfHunter => BLOOD_ELF_HUNTER,
        RaceClass::BloodElfRogue => BLOOD_ELF_ROGUE,
        RaceClass::BloodElfPriest => BLOOD_ELF_PRIEST,
        RaceClass::BloodElfMage => BLOOD_ELF_MAGE,
        RaceClass::BloodElfWarlock => BLOOD_ELF_WARLOCK,
        RaceClass::HumanDeathKnight => HUMAN_DEATH_KNIGHT,
        RaceClass::OrcDeathKnight => ORC_DEATH_KNIGHT,
        RaceClass::DwarfDeathKnight => DWARF_DEATH_KNIGHT,
        RaceClass::NightElfDeathKnight => NIGHT_ELF_DEATH_KNIGHT,
        RaceClass::UndeadDeathKnight => UNDEAD_DEATH_KNIGHT,
        RaceClass::TaurenDeathKnight => TAUREN_DEATH_KNIGHT,
        RaceClass::GnomeDeathKnight => GNOME_DEATH_KNIGHT,
        RaceClass::TrollDeathKnight => TROLL_DEATH_KNIGHT,
        RaceClass::BloodElfDeathKnight => BLOOD_ELF_DEATH_KNIGHT,
        RaceClass::DraeneiDeathKnight => DRAENEI_DEATH_KNIGHT,
    }
}

// AUTOGENERATED_START
const HUMAN_WARRIOR: &[u32] = &[
    26, // Warrior: Arms
    43, // Weapon: Swords (Warrior)
    44, // Weapon: Axes (Warrior)
    54, // Weapon: Maces (Warrior)
    95, // Misc: Defense
    98, // Language: Common
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    256, // Warrior: Fury
    257, // Warrior: Protection
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
    754, // Racial: Human
];
const HUMAN_PALADIN: &[u32] = &[
    54, // Weapon: Maces (Paladin)
    95, // Misc: Defense
    98, // Language: Common
    160, // Weapon: Two-Handed Maces (Paladin)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    184, // Paladin: Retribution
    267, // Paladin: Protection
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
    594, // Paladin: Holy
    754, // Racial: Human
];
const HUMAN_ROGUE: &[u32] = &[
    38, // Rogue: Combat
    39, // Rogue: Subtlety
    95, // Misc: Defense
    98, // Language: Common
    118, // Misc: Dual Wield
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Rogue)
    176, // Weapon: Thrown (Rogue)
    183, // Misc: GENERIC (DND)
    253, // Rogue: Assassination
    414, // Armor: Leather
    415, // Armor: Cloth
    754, // Racial: Human
];
const HUMAN_PRIEST: &[u32] = &[
    54, // Weapon: Maces (Priest)
    56, // Priest: Holy
    78, // Priest: Shadow
    95, // Misc: Defense
    98, // Language: Common
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Priest)
    415, // Armor: Cloth
    613, // Priest: Discipline
    754, // Racial: Human
];
const HUMAN_DEATH_KNIGHT: &[u32] = &[
    43, // Weapon: Swords (Death Knight)
    44, // Weapon: Axes (Death Knight)
    55, // Weapon: Two-Handed Swords (Death Knight)
    95, // Misc: Defense
    98, // Language: Common
    118, // Misc: Dual Wield
    129, // Secondary: First Aid
    162, // Weapon: Unarmed
    172, // Weapon: Two-Handed Axes (Death Knight)
    183, // Misc: GENERIC (DND)
    229, // Weapon: Polearms (Death Knight)
    293, // Armor: Plate
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    754, // Racial: Human
    762, // Secondary: Riding
    770, // Death Knight: Blood
    771, // Death Knight: Frost
    772, // Death Knight: Unholy
];
const HUMAN_MAGE: &[u32] = &[
    6, // Mage: Frost
    8, // Mage: Fire
    95, // Misc: Defense
    98, // Language: Common
    136, // Weapon: Staves (Mage)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Mage)
    237, // Mage: Arcane
    415, // Armor: Cloth
    754, // Racial: Human
];
const HUMAN_WARLOCK: &[u32] = &[
    95, // Misc: Defense
    98, // Language: Common
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Warlock)
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Warlock)
    354, // Warlock: Demonology
    355, // Warlock: Affliction
    415, // Armor: Cloth
    593, // Warlock: Destruction
    754, // Racial: Human
];
const ORC_WARRIOR: &[u32] = &[
    26, // Warrior: Arms
    43, // Weapon: Swords (Warrior)
    44, // Weapon: Axes (Warrior)
    95, // Misc: Defense
    109, // Language: Orcish
    125, // Racial: Orc
    162, // Weapon: Unarmed
    172, // Weapon: Two-Handed Axes (Warrior)
    183, // Misc: GENERIC (DND)
    256, // Warrior: Fury
    257, // Warrior: Protection
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
];
const ORC_HUNTER: &[u32] = &[
    44, // Weapon: Axes (Hunter)
    45, // Weapon: Bows (Hunter)
    50, // Hunter: Beast Mastery
    51, // Hunter: Survival
    95, // Misc: Defense
    109, // Language: Orcish
    125, // Racial: Orc
    162, // Weapon: Unarmed
    163, // Hunter: Marksmanship
    183, // Misc: GENERIC (DND)
    414, // Armor: Leather
    415, // Armor: Cloth
];
const ORC_ROGUE: &[u32] = &[
    38, // Rogue: Combat
    39, // Rogue: Subtlety
    95, // Misc: Defense
    109, // Language: Orcish
    118, // Misc: Dual Wield
    125, // Racial: Orc
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Rogue)
    176, // Weapon: Thrown (Rogue)
    183, // Misc: GENERIC (DND)
    253, // Rogue: Assassination
    414, // Armor: Leather
    415, // Armor: Cloth
];
const ORC_DEATH_KNIGHT: &[u32] = &[
    43, // Weapon: Swords (Death Knight)
    44, // Weapon: Axes (Death Knight)
    55, // Weapon: Two-Handed Swords (Death Knight)
    95, // Misc: Defense
    109, // Language: Orcish
    118, // Misc: Dual Wield
    125, // Racial: Orc
    129, // Secondary: First Aid
    162, // Weapon: Unarmed
    172, // Weapon: Two-Handed Axes (Death Knight)
    183, // Misc: GENERIC (DND)
    229, // Weapon: Polearms (Death Knight)
    293, // Armor: Plate
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    762, // Secondary: Riding
    770, // Death Knight: Blood
    771, // Death Knight: Frost
    772, // Death Knight: Unholy
];
const ORC_SHAMAN: &[u32] = &[
    54, // Weapon: Maces (Shaman)
    95, // Misc: Defense
    109, // Language: Orcish
    125, // Racial: Orc
    136, // Weapon: Staves (Shaman)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    373, // Shaman: Enhancement
    374, // Shaman: Restoration
    375, // Shaman: Elemental
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
];
const ORC_WARLOCK: &[u32] = &[
    95, // Misc: Defense
    109, // Language: Orcish
    125, // Racial: Orc
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Warlock)
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Warlock)
    354, // Warlock: Demonology
    355, // Warlock: Affliction
    415, // Armor: Cloth
    593, // Warlock: Destruction
];
const DWARF_WARRIOR: &[u32] = &[
    26, // Warrior: Arms
    44, // Weapon: Axes (Warrior)
    54, // Weapon: Maces (Warrior)
    95, // Misc: Defense
    98, // Language: Common
    101, // Racial: Dwarf
    111, // Language: Dwarven
    162, // Weapon: Unarmed
    172, // Weapon: Two-Handed Axes (Warrior)
    183, // Misc: GENERIC (DND)
    256, // Warrior: Fury
    257, // Warrior: Protection
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
];
const DWARF_PALADIN: &[u32] = &[
    54, // Weapon: Maces (Paladin)
    95, // Misc: Defense
    98, // Language: Common
    101, // Racial: Dwarf
    111, // Language: Dwarven
    160, // Weapon: Two-Handed Maces (Paladin)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    184, // Paladin: Retribution
    267, // Paladin: Protection
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
    594, // Paladin: Holy
];
const DWARF_HUNTER: &[u32] = &[
    44, // Weapon: Axes (Hunter)
    46, // Weapon: Guns (Hunter)
    50, // Hunter: Beast Mastery
    51, // Hunter: Survival
    95, // Misc: Defense
    98, // Language: Common
    101, // Racial: Dwarf
    111, // Language: Dwarven
    162, // Weapon: Unarmed
    163, // Hunter: Marksmanship
    183, // Misc: GENERIC (DND)
    414, // Armor: Leather
    415, // Armor: Cloth
];
const DWARF_ROGUE: &[u32] = &[
    38, // Rogue: Combat
    39, // Rogue: Subtlety
    95, // Misc: Defense
    98, // Language: Common
    101, // Racial: Dwarf
    111, // Language: Dwarven
    118, // Misc: Dual Wield
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Rogue)
    176, // Weapon: Thrown (Rogue)
    183, // Misc: GENERIC (DND)
    253, // Rogue: Assassination
    414, // Armor: Leather
    415, // Armor: Cloth
];
const DWARF_PRIEST: &[u32] = &[
    54, // Weapon: Maces (Priest)
    56, // Priest: Holy
    78, // Priest: Shadow
    95, // Misc: Defense
    98, // Language: Common
    101, // Racial: Dwarf
    111, // Language: Dwarven
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Priest)
    415, // Armor: Cloth
    613, // Priest: Discipline
];
const DWARF_DEATH_KNIGHT: &[u32] = &[
    43, // Weapon: Swords (Death Knight)
    44, // Weapon: Axes (Death Knight)
    55, // Weapon: Two-Handed Swords (Death Knight)
    95, // Misc: Defense
    98, // Language: Common
    101, // Racial: Dwarf
    111, // Language: Dwarven
    118, // Misc: Dual Wield
    129, // Secondary: First Aid
    162, // Weapon: Unarmed
    172, // Weapon: Two-Handed Axes (Death Knight)
    183, // Misc: GENERIC (DND)
    229, // Weapon: Polearms (Death Knight)
    293, // Armor: Plate
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    762, // Secondary: Riding
    770, // Death Knight: Blood
    771, // Death Knight: Frost
    772, // Death Knight: Unholy
];
const NIGHT_ELF_WARRIOR: &[u32] = &[
    26, // Warrior: Arms
    43, // Weapon: Swords (Warrior)
    54, // Weapon: Maces (Warrior)
    95, // Misc: Defense
    98, // Language: Common
    113, // Language: Darnassian
    126, // Racial: Night Elf
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Warrior)
    183, // Misc: GENERIC (DND)
    256, // Warrior: Fury
    257, // Warrior: Protection
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
];
const NIGHT_ELF_HUNTER: &[u32] = &[
    45, // Weapon: Bows (Hunter)
    50, // Hunter: Beast Mastery
    51, // Hunter: Survival
    95, // Misc: Defense
    98, // Language: Common
    113, // Language: Darnassian
    126, // Racial: Night Elf
    162, // Weapon: Unarmed
    163, // Hunter: Marksmanship
    173, // Weapon: Daggers (Hunter)
    183, // Misc: GENERIC (DND)
    414, // Armor: Leather
    415, // Armor: Cloth
];
const NIGHT_ELF_ROGUE: &[u32] = &[
    38, // Rogue: Combat
    39, // Rogue: Subtlety
    95, // Misc: Defense
    98, // Language: Common
    113, // Language: Darnassian
    118, // Misc: Dual Wield
    126, // Racial: Night Elf
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Rogue)
    176, // Weapon: Thrown (Rogue)
    183, // Misc: GENERIC (DND)
    253, // Rogue: Assassination
    414, // Armor: Leather
    415, // Armor: Cloth
];
const NIGHT_ELF_PRIEST: &[u32] = &[
    54, // Weapon: Maces (Priest)
    56, // Priest: Holy
    78, // Priest: Shadow
    95, // Misc: Defense
    98, // Language: Common
    113, // Language: Darnassian
    126, // Racial: Night Elf
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Priest)
    415, // Armor: Cloth
    613, // Priest: Discipline
];
const NIGHT_ELF_DEATH_KNIGHT: &[u32] = &[
    43, // Weapon: Swords (Death Knight)
    44, // Weapon: Axes (Death Knight)
    55, // Weapon: Two-Handed Swords (Death Knight)
    95, // Misc: Defense
    98, // Language: Common
    113, // Language: Darnassian
    118, // Misc: Dual Wield
    126, // Racial: Night Elf
    129, // Secondary: First Aid
    162, // Weapon: Unarmed
    172, // Weapon: Two-Handed Axes (Death Knight)
    183, // Misc: GENERIC (DND)
    229, // Weapon: Polearms (Death Knight)
    293, // Armor: Plate
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    762, // Secondary: Riding
    770, // Death Knight: Blood
    771, // Death Knight: Frost
    772, // Death Knight: Unholy
];
const NIGHT_ELF_DRUID: &[u32] = &[
    95, // Misc: Defense
    98, // Language: Common
    113, // Language: Darnassian
    126, // Racial: Night Elf
    134, // Druid: Feral
    136, // Weapon: Staves (Druid)
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Druid)
    183, // Misc: GENERIC (DND)
    414, // Armor: Leather
    415, // Armor: Cloth
    573, // Druid: Restoration
    574, // Druid: Balance
];
const UNDEAD_WARRIOR: &[u32] = &[
    26, // Warrior: Arms
    43, // Weapon: Swords (Warrior)
    55, // Weapon: Two-Handed Swords (Warrior)
    95, // Misc: Defense
    109, // Language: Orcish
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Warrior)
    183, // Misc: GENERIC (DND)
    220, // Racial: Undead
    256, // Warrior: Fury
    257, // Warrior: Protection
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
    673, // Language: Gutterspeak
];
const UNDEAD_ROGUE: &[u32] = &[
    38, // Rogue: Combat
    39, // Rogue: Subtlety
    95, // Misc: Defense
    109, // Language: Orcish
    118, // Misc: Dual Wield
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Rogue)
    176, // Weapon: Thrown (Rogue)
    183, // Misc: GENERIC (DND)
    220, // Racial: Undead
    253, // Rogue: Assassination
    414, // Armor: Leather
    415, // Armor: Cloth
    673, // Language: Gutterspeak
];
const UNDEAD_PRIEST: &[u32] = &[
    54, // Weapon: Maces (Priest)
    56, // Priest: Holy
    78, // Priest: Shadow
    95, // Misc: Defense
    109, // Language: Orcish
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    220, // Racial: Undead
    228, // Weapon: Wands (Priest)
    415, // Armor: Cloth
    613, // Priest: Discipline
    673, // Language: Gutterspeak
];
const UNDEAD_DEATH_KNIGHT: &[u32] = &[
    43, // Weapon: Swords (Death Knight)
    44, // Weapon: Axes (Death Knight)
    55, // Weapon: Two-Handed Swords (Death Knight)
    95, // Misc: Defense
    109, // Language: Orcish
    118, // Misc: Dual Wield
    129, // Secondary: First Aid
    162, // Weapon: Unarmed
    172, // Weapon: Two-Handed Axes (Death Knight)
    183, // Misc: GENERIC (DND)
    220, // Racial: Undead
    229, // Weapon: Polearms (Death Knight)
    293, // Armor: Plate
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    673, // Language: Gutterspeak
    762, // Secondary: Riding
    770, // Death Knight: Blood
    771, // Death Knight: Frost
    772, // Death Knight: Unholy
];
const UNDEAD_MAGE: &[u32] = &[
    6, // Mage: Frost
    8, // Mage: Fire
    95, // Misc: Defense
    109, // Language: Orcish
    136, // Weapon: Staves (Mage)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    220, // Racial: Undead
    228, // Weapon: Wands (Mage)
    237, // Mage: Arcane
    415, // Armor: Cloth
    673, // Language: Gutterspeak
];
const UNDEAD_WARLOCK: &[u32] = &[
    95, // Misc: Defense
    109, // Language: Orcish
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Warlock)
    183, // Misc: GENERIC (DND)
    220, // Racial: Undead
    228, // Weapon: Wands (Warlock)
    354, // Warlock: Demonology
    355, // Warlock: Affliction
    415, // Armor: Cloth
    593, // Warlock: Destruction
    673, // Language: Gutterspeak
];
const TAUREN_WARRIOR: &[u32] = &[
    26, // Warrior: Arms
    44, // Weapon: Axes (Warrior)
    54, // Weapon: Maces (Warrior)
    95, // Misc: Defense
    109, // Language: Orcish
    115, // Language: Taurahe
    124, // Racial: Tauren
    160, // Weapon: Two-Handed Maces (Warrior)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    256, // Warrior: Fury
    257, // Warrior: Protection
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
];
const TAUREN_HUNTER: &[u32] = &[
    44, // Weapon: Axes (Hunter)
    46, // Weapon: Guns (Hunter)
    50, // Hunter: Beast Mastery
    51, // Hunter: Survival
    95, // Misc: Defense
    109, // Language: Orcish
    115, // Language: Taurahe
    124, // Racial: Tauren
    162, // Weapon: Unarmed
    163, // Hunter: Marksmanship
    183, // Misc: GENERIC (DND)
    414, // Armor: Leather
    415, // Armor: Cloth
];
const TAUREN_DEATH_KNIGHT: &[u32] = &[
    43, // Weapon: Swords (Death Knight)
    44, // Weapon: Axes (Death Knight)
    55, // Weapon: Two-Handed Swords (Death Knight)
    95, // Misc: Defense
    109, // Language: Orcish
    115, // Language: Taurahe
    118, // Misc: Dual Wield
    124, // Racial: Tauren
    129, // Secondary: First Aid
    162, // Weapon: Unarmed
    172, // Weapon: Two-Handed Axes (Death Knight)
    183, // Misc: GENERIC (DND)
    229, // Weapon: Polearms (Death Knight)
    293, // Armor: Plate
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    762, // Secondary: Riding
    770, // Death Knight: Blood
    771, // Death Knight: Frost
    772, // Death Knight: Unholy
];
const TAUREN_SHAMAN: &[u32] = &[
    54, // Weapon: Maces (Shaman)
    95, // Misc: Defense
    109, // Language: Orcish
    115, // Language: Taurahe
    124, // Racial: Tauren
    136, // Weapon: Staves (Shaman)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    373, // Shaman: Enhancement
    374, // Shaman: Restoration
    375, // Shaman: Elemental
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
];
const TAUREN_DRUID: &[u32] = &[
    54, // Weapon: Maces (Druid)
    95, // Misc: Defense
    109, // Language: Orcish
    115, // Language: Taurahe
    124, // Racial: Tauren
    134, // Druid: Feral
    136, // Weapon: Staves (Druid)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    414, // Armor: Leather
    415, // Armor: Cloth
    573, // Druid: Restoration
    574, // Druid: Balance
];
const GNOME_WARRIOR: &[u32] = &[
    26, // Warrior: Arms
    43, // Weapon: Swords (Warrior)
    54, // Weapon: Maces (Warrior)
    95, // Misc: Defense
    98, // Language: Common
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Warrior)
    183, // Misc: GENERIC (DND)
    256, // Warrior: Fury
    257, // Warrior: Protection
    313, // Language: Gnomish
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
    753, // Racial: Gnome
];
const GNOME_ROGUE: &[u32] = &[
    38, // Rogue: Combat
    39, // Rogue: Subtlety
    95, // Misc: Defense
    98, // Language: Common
    118, // Misc: Dual Wield
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Rogue)
    176, // Weapon: Thrown (Rogue)
    183, // Misc: GENERIC (DND)
    253, // Rogue: Assassination
    313, // Language: Gnomish
    414, // Armor: Leather
    415, // Armor: Cloth
    753, // Racial: Gnome
];
const GNOME_DEATH_KNIGHT: &[u32] = &[
    43, // Weapon: Swords (Death Knight)
    44, // Weapon: Axes (Death Knight)
    55, // Weapon: Two-Handed Swords (Death Knight)
    95, // Misc: Defense
    98, // Language: Common
    118, // Misc: Dual Wield
    129, // Secondary: First Aid
    162, // Weapon: Unarmed
    172, // Weapon: Two-Handed Axes (Death Knight)
    183, // Misc: GENERIC (DND)
    229, // Weapon: Polearms (Death Knight)
    293, // Armor: Plate
    313, // Language: Gnomish
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    753, // Racial: Gnome
    762, // Secondary: Riding
    770, // Death Knight: Blood
    771, // Death Knight: Frost
    772, // Death Knight: Unholy
];
const GNOME_MAGE: &[u32] = &[
    6, // Mage: Frost
    8, // Mage: Fire
    95, // Misc: Defense
    98, // Language: Common
    136, // Weapon: Staves (Mage)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Mage)
    237, // Mage: Arcane
    313, // Language: Gnomish
    415, // Armor: Cloth
    753, // Racial: Gnome
];
const GNOME_WARLOCK: &[u32] = &[
    95, // Misc: Defense
    98, // Language: Common
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Warlock)
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Warlock)
    313, // Language: Gnomish
    354, // Warlock: Demonology
    355, // Warlock: Affliction
    415, // Armor: Cloth
    593, // Warlock: Destruction
    753, // Racial: Gnome
];
const TROLL_WARRIOR: &[u32] = &[
    26, // Warrior: Arms
    44, // Weapon: Axes (Warrior)
    95, // Misc: Defense
    109, // Language: Orcish
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Warrior)
    176, // Weapon: Thrown (Warrior)
    183, // Misc: GENERIC (DND)
    256, // Warrior: Fury
    257, // Warrior: Protection
    315, // Language: Troll
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
    733, // Racial: Troll
];
const TROLL_HUNTER: &[u32] = &[
    44, // Weapon: Axes (Hunter)
    45, // Weapon: Bows (Hunter)
    50, // Hunter: Beast Mastery
    51, // Hunter: Survival
    95, // Misc: Defense
    109, // Language: Orcish
    162, // Weapon: Unarmed
    163, // Hunter: Marksmanship
    183, // Misc: GENERIC (DND)
    315, // Language: Troll
    414, // Armor: Leather
    415, // Armor: Cloth
    733, // Racial: Troll
];
const TROLL_ROGUE: &[u32] = &[
    38, // Rogue: Combat
    39, // Rogue: Subtlety
    95, // Misc: Defense
    109, // Language: Orcish
    118, // Misc: Dual Wield
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Rogue)
    176, // Weapon: Thrown (Rogue)
    183, // Misc: GENERIC (DND)
    253, // Rogue: Assassination
    315, // Language: Troll
    414, // Armor: Leather
    415, // Armor: Cloth
    733, // Racial: Troll
];
const TROLL_PRIEST: &[u32] = &[
    54, // Weapon: Maces (Priest)
    56, // Priest: Holy
    78, // Priest: Shadow
    95, // Misc: Defense
    109, // Language: Orcish
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Priest)
    315, // Language: Troll
    415, // Armor: Cloth
    613, // Priest: Discipline
    733, // Racial: Troll
];
const TROLL_DEATH_KNIGHT: &[u32] = &[
    43, // Weapon: Swords (Death Knight)
    44, // Weapon: Axes (Death Knight)
    55, // Weapon: Two-Handed Swords (Death Knight)
    95, // Misc: Defense
    109, // Language: Orcish
    118, // Misc: Dual Wield
    129, // Secondary: First Aid
    162, // Weapon: Unarmed
    172, // Weapon: Two-Handed Axes (Death Knight)
    183, // Misc: GENERIC (DND)
    229, // Weapon: Polearms (Death Knight)
    293, // Armor: Plate
    315, // Language: Troll
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    733, // Racial: Troll
    762, // Secondary: Riding
    770, // Death Knight: Blood
    771, // Death Knight: Frost
    772, // Death Knight: Unholy
];
const TROLL_SHAMAN: &[u32] = &[
    54, // Weapon: Maces (Shaman)
    95, // Misc: Defense
    109, // Language: Orcish
    136, // Weapon: Staves (Shaman)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    315, // Language: Troll
    373, // Shaman: Enhancement
    374, // Shaman: Restoration
    375, // Shaman: Elemental
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
    733, // Racial: Troll
];
const TROLL_MAGE: &[u32] = &[
    6, // Mage: Frost
    8, // Mage: Fire
    95, // Misc: Defense
    109, // Language: Orcish
    136, // Weapon: Staves (Mage)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Mage)
    237, // Mage: Arcane
    315, // Language: Troll
    415, // Armor: Cloth
    733, // Racial: Troll
];
const BLOOD_ELF_PALADIN: &[u32] = &[
    43, // Weapon: Swords (Paladin)
    55, // Weapon: Two-Handed Swords (Paladin)
    95, // Misc: Defense
    109, // Language: Orcish
    137, // Language: Thalassian
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    184, // Paladin: Retribution
    267, // Paladin: Protection
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
    594, // Paladin: Holy
    756, // Racial: Blood Elf
];
const BLOOD_ELF_HUNTER: &[u32] = &[
    45, // Weapon: Bows (Hunter)
    50, // Hunter: Beast Mastery
    51, // Hunter: Survival
    95, // Misc: Defense
    109, // Language: Orcish
    137, // Language: Thalassian
    162, // Weapon: Unarmed
    163, // Hunter: Marksmanship
    173, // Weapon: Daggers (Hunter)
    183, // Misc: GENERIC (DND)
    414, // Armor: Leather
    415, // Armor: Cloth
    756, // Racial: Blood Elf
];
const BLOOD_ELF_ROGUE: &[u32] = &[
    38, // Rogue: Combat
    39, // Rogue: Subtlety
    95, // Misc: Defense
    109, // Language: Orcish
    118, // Misc: Dual Wield
    137, // Language: Thalassian
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Rogue)
    176, // Weapon: Thrown (Rogue)
    183, // Misc: GENERIC (DND)
    253, // Rogue: Assassination
    414, // Armor: Leather
    415, // Armor: Cloth
    756, // Racial: Blood Elf
];
const BLOOD_ELF_PRIEST: &[u32] = &[
    54, // Weapon: Maces (Priest)
    56, // Priest: Holy
    78, // Priest: Shadow
    95, // Misc: Defense
    109, // Language: Orcish
    137, // Language: Thalassian
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Priest)
    415, // Armor: Cloth
    613, // Priest: Discipline
    756, // Racial: Blood Elf
];
const BLOOD_ELF_DEATH_KNIGHT: &[u32] = &[
    43, // Weapon: Swords (Death Knight)
    44, // Weapon: Axes (Death Knight)
    55, // Weapon: Two-Handed Swords (Death Knight)
    95, // Misc: Defense
    109, // Language: Orcish
    118, // Misc: Dual Wield
    129, // Secondary: First Aid
    137, // Language: Thalassian
    162, // Weapon: Unarmed
    172, // Weapon: Two-Handed Axes (Death Knight)
    183, // Misc: GENERIC (DND)
    229, // Weapon: Polearms (Death Knight)
    293, // Armor: Plate
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    756, // Racial: Blood Elf
    762, // Secondary: Riding
    770, // Death Knight: Blood
    771, // Death Knight: Frost
    772, // Death Knight: Unholy
];
const BLOOD_ELF_MAGE: &[u32] = &[
    6, // Mage: Frost
    8, // Mage: Fire
    95, // Misc: Defense
    109, // Language: Orcish
    136, // Weapon: Staves (Mage)
    137, // Language: Thalassian
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Mage)
    237, // Mage: Arcane
    415, // Armor: Cloth
    756, // Racial: Blood Elf
];
const BLOOD_ELF_WARLOCK: &[u32] = &[
    95, // Misc: Defense
    109, // Language: Orcish
    137, // Language: Thalassian
    162, // Weapon: Unarmed
    173, // Weapon: Daggers (Warlock)
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Warlock)
    354, // Warlock: Demonology
    355, // Warlock: Affliction
    415, // Armor: Cloth
    593, // Warlock: Destruction
    756, // Racial: Blood Elf
];
const DRAENEI_WARRIOR: &[u32] = &[
    26, // Warrior: Arms
    43, // Weapon: Swords (Warrior)
    54, // Weapon: Maces (Warrior)
    55, // Weapon: Two-Handed Swords (Warrior)
    95, // Misc: Defense
    98, // Language: Common
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    256, // Warrior: Fury
    257, // Warrior: Protection
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
    759, // Language: Draenei
    760, // Racial: Draenei
];
const DRAENEI_PALADIN: &[u32] = &[
    54, // Weapon: Maces (Paladin)
    95, // Misc: Defense
    98, // Language: Common
    160, // Weapon: Two-Handed Maces (Paladin)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    184, // Paladin: Retribution
    267, // Paladin: Protection
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
    594, // Paladin: Holy
    759, // Language: Draenei
    760, // Racial: Draenei
];
const DRAENEI_HUNTER: &[u32] = &[
    43, // Weapon: Swords (Hunter)
    50, // Hunter: Beast Mastery
    51, // Hunter: Survival
    95, // Misc: Defense
    98, // Language: Common
    162, // Weapon: Unarmed
    163, // Hunter: Marksmanship
    183, // Misc: GENERIC (DND)
    226, // Weapon: Crossbows (Hunter)
    414, // Armor: Leather
    415, // Armor: Cloth
    759, // Language: Draenei
    760, // Racial: Draenei
];
const DRAENEI_PRIEST: &[u32] = &[
    54, // Weapon: Maces (Priest)
    56, // Priest: Holy
    78, // Priest: Shadow
    95, // Misc: Defense
    98, // Language: Common
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Priest)
    415, // Armor: Cloth
    613, // Priest: Discipline
    759, // Language: Draenei
    760, // Racial: Draenei
];
const DRAENEI_DEATH_KNIGHT: &[u32] = &[
    43, // Weapon: Swords (Death Knight)
    44, // Weapon: Axes (Death Knight)
    55, // Weapon: Two-Handed Swords (Death Knight)
    95, // Misc: Defense
    98, // Language: Common
    118, // Misc: Dual Wield
    129, // Secondary: First Aid
    162, // Weapon: Unarmed
    172, // Weapon: Two-Handed Axes (Death Knight)
    183, // Misc: GENERIC (DND)
    229, // Weapon: Polearms (Death Knight)
    293, // Armor: Plate
    413, // Armor: Mail
    414, // Armor: Leather
    415, // Armor: Cloth
    759, // Language: Draenei
    760, // Racial: Draenei
    762, // Secondary: Riding
    770, // Death Knight: Blood
    771, // Death Knight: Frost
    772, // Death Knight: Unholy
];
const DRAENEI_SHAMAN: &[u32] = &[
    54, // Weapon: Maces (Shaman)
    95, // Misc: Defense
    98, // Language: Common
    136, // Weapon: Staves (Shaman)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    373, // Shaman: Enhancement
    374, // Shaman: Restoration
    375, // Shaman: Elemental
    414, // Armor: Leather
    415, // Armor: Cloth
    433, // Armor: Shield
    759, // Language: Draenei
    760, // Racial: Draenei
];
const DRAENEI_MAGE: &[u32] = &[
    6, // Mage: Frost
    8, // Mage: Fire
    95, // Misc: Defense
    98, // Language: Common
    136, // Weapon: Staves (Mage)
    162, // Weapon: Unarmed
    183, // Misc: GENERIC (DND)
    228, // Weapon: Wands (Mage)
    237, // Mage: Arcane
    415, // Armor: Cloth
    759, // Language: Draenei
    760, // Racial: Draenei
];
// AUTOGENERATED_END
