[package]
name = "tbc_server"
version = "0.0.0"
edition = "2018"
publish = false
metadata.release.release = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.18.2", features = ["full"] }
wow_login_messages = { path = "../../wow_login_messages", features = ["tokio"] }
wow_world_messages = { path = "../../wow_world_messages", features = ["tokio", "tbc"] }

[dependencies.wow_srp]
version = "0.7.0"
