use crate::tbc::{InventoryType, ItemQuality};

#[derive(Debug, Copy, Clone)]
pub struct Item {
    pub entry: i32,
    pub class: i32,
    pub subclass: i32,
    pub sound_override_subclass: i32,
    pub name: &'static str,
    pub displayid: i32,
    pub quality: ItemQuality,
    pub flags: i32,
    pub buy_count: i32,
    pub buy_price: i32,
    pub sell_price: i32,
    pub inventory_type: InventoryType,
    pub allowed_class: i32,
    pub allowed_race: i32,
    pub item_level: i32,
    pub required_level: i32,
    pub required_skill: i32,
    pub required_skill_rank: i32,
    pub required_spell: i32,
    pub required_honor_rank: i32,
    pub required_city_rank: i32,
    pub required_reputation_faction: i32,
    pub required_reputation_rank: i32,
    pub max_count: i32,
    pub stackable: i32,
    pub container_slots: i32,
    pub stat_type1: i32,
    pub stat_value1: i32,
    pub stat_type2: i32,
    pub stat_value2: i32,
    pub stat_type3: i32,
    pub stat_value3: i32,
    pub stat_type4: i32,
    pub stat_value4: i32,
    pub stat_type5: i32,
    pub stat_value5: i32,
    pub stat_type6: i32,
    pub stat_value6: i32,
    pub stat_type7: i32,
    pub stat_value7: i32,
    pub dmg_min1: f32,
    pub dmg_max1: f32,
    pub dmg_type1: i32,
    pub dmg_min2: f32,
    pub dmg_max2: f32,
    pub dmg_type2: i32,
    pub dmg_min3: f32,
    pub dmg_max3: f32,
    pub dmg_type3: i32,
    pub dmg_min4: f32,
    pub dmg_max4: f32,
    pub dmg_type4: i32,
    pub dmg_min5: f32,
    pub dmg_max5: f32,
    pub dmg_type5: i32,
    pub armor: i32,
    pub holy_res: i32,
    pub fire_res: i32,
    pub nature_res: i32,
    pub frost_res: i32,
    pub shadow_res: i32,
    pub arcane_res: i32,
    pub delay: i32,
    pub ammo_type: i32,
    pub ranged_mod_range: f32,
    pub spell_id_1: i32,
    pub spell_trigger_1: i32,
    pub spell_charges_1: i32,
    pub spell_ppm_rate_1: f32,
    pub spell_cooldown_1: i32,
    pub spell_category_1: i32,
    pub spell_category_cooldown_1: i32,
    pub spell_id_2: i32,
    pub spell_trigger_2: i32,
    pub spell_charges_2: i32,
    pub spell_ppm_rate_2: f32,
    pub spell_cooldown_2: i32,
    pub spell_category_2: i32,
    pub spell_category_cooldown_2: i32,
    pub spell_id_3: i32,
    pub spell_trigger_3: i32,
    pub spell_charges_3: i32,
    pub spell_ppm_rate_3: f32,
    pub spell_cooldown_3: i32,
    pub spell_category_3: i32,
    pub spell_category_cooldown_3: i32,
    pub spell_id_4: i32,
    pub spell_trigger_4: i32,
    pub spell_charges_4: i32,
    pub spell_ppm_rate_4: f32,
    pub spell_cooldown_4: i32,
    pub spell_category_4: i32,
    pub spell_category_cooldown_4: i32,
    pub spell_id_5: i32,
    pub spell_trigger_5: i32,
    pub spell_charges_5: i32,
    pub spell_ppm_rate_5: f32,
    pub spell_cooldown_5: i32,
    pub spell_category_5: i32,
    pub spell_category_cooldown_5: i32,
    pub bonding: i32,
    pub description: &'static str,
    pub page_text: i32,
    pub language_id: i32,
    pub page_material: i32,
    pub start_quest: i32,
    pub lock_id: i32,
    pub material: i32,
    pub sheath: i32,
    pub random_property: i32,
    pub random_suffix: i32,
    pub block: i32,
    pub itemset: i32,
    pub max_durability: i32,
    pub area: i32,
    pub map: i32,
    pub bag_family: i32,
    pub totem_category: i32,
    pub socket_color_1: i32,
    pub socket_content_1: i32,
    pub socket_color_2: i32,
    pub socket_content_2: i32,
    pub socket_color_3: i32,
    pub socket_content_3: i32,
    pub socket_bonus: i32,
    pub gem_properties: i32,
    pub required_disenchant_skill: i32,
    pub armor_damage_modifier: f32,
    pub script_name: &'static str,
    pub disenchant_id: i32,
    pub food_type: i32,
    pub min_money_loot: i32,
    pub max_money_loot: i32,
    pub duration: i32,
    pub extra_flags: i32,
}

impl Item {
    #[allow(clippy::complexity)]
    pub const fn new(
        entry: i32,
        class: i32,
        subclass: i32,
        sound_override_subclass: i32,
        name: &'static str,
        displayid: i32,
        quality: ItemQuality,
        flags: i32,
        buy_count: i32,
        buy_price: i32,
        sell_price: i32,
        inventory_type: InventoryType,
        allowed_class: i32,
        allowed_race: i32,
        item_level: i32,
        required_level: i32,
        required_skill: i32,
        required_skill_rank: i32,
        required_spell: i32,
        required_honor_rank: i32,
        required_city_rank: i32,
        required_reputation_faction: i32,
        required_reputation_rank: i32,
        max_count: i32,
        stackable: i32,
        container_slots: i32,
        stat_type1: i32,
        stat_value1: i32,
        stat_type2: i32,
        stat_value2: i32,
        stat_type3: i32,
        stat_value3: i32,
        stat_type4: i32,
        stat_value4: i32,
        stat_type5: i32,
        stat_value5: i32,
        stat_type6: i32,
        stat_value6: i32,
        stat_type7: i32,
        stat_value7: i32,
        dmg_min1: f32,
        dmg_max1: f32,
        dmg_type1: i32,
        dmg_min2: f32,
        dmg_max2: f32,
        dmg_type2: i32,
        dmg_min3: f32,
        dmg_max3: f32,
        dmg_type3: i32,
        dmg_min4: f32,
        dmg_max4: f32,
        dmg_type4: i32,
        dmg_min5: f32,
        dmg_max5: f32,
        dmg_type5: i32,
        armor: i32,
        holy_res: i32,
        fire_res: i32,
        nature_res: i32,
        frost_res: i32,
        shadow_res: i32,
        arcane_res: i32,
        delay: i32,
        ammo_type: i32,
        ranged_mod_range: f32,
        spell_id_1: i32,
        spell_trigger_1: i32,
        spell_charges_1: i32,
        spell_ppm_rate_1: f32,
        spell_cooldown_1: i32,
        spell_category_1: i32,
        spell_category_cooldown_1: i32,
        spell_id_2: i32,
        spell_trigger_2: i32,
        spell_charges_2: i32,
        spell_ppm_rate_2: f32,
        spell_cooldown_2: i32,
        spell_category_2: i32,
        spell_category_cooldown_2: i32,
        spell_id_3: i32,
        spell_trigger_3: i32,
        spell_charges_3: i32,
        spell_ppm_rate_3: f32,
        spell_cooldown_3: i32,
        spell_category_3: i32,
        spell_category_cooldown_3: i32,
        spell_id_4: i32,
        spell_trigger_4: i32,
        spell_charges_4: i32,
        spell_ppm_rate_4: f32,
        spell_cooldown_4: i32,
        spell_category_4: i32,
        spell_category_cooldown_4: i32,
        spell_id_5: i32,
        spell_trigger_5: i32,
        spell_charges_5: i32,
        spell_ppm_rate_5: f32,
        spell_cooldown_5: i32,
        spell_category_5: i32,
        spell_category_cooldown_5: i32,
        bonding: i32,
        description: &'static str,
        page_text: i32,
        language_id: i32,
        page_material: i32,
        start_quest: i32,
        lock_id: i32,
        material: i32,
        sheath: i32,
        random_property: i32,
        random_suffix: i32,
        block: i32,
        itemset: i32,
        max_durability: i32,
        area: i32,
        map: i32,
        bag_family: i32,
        totem_category: i32,
        socket_color_1: i32,
        socket_content_1: i32,
        socket_color_2: i32,
        socket_content_2: i32,
        socket_color_3: i32,
        socket_content_3: i32,
        socket_bonus: i32,
        gem_properties: i32,
        required_disenchant_skill: i32,
        armor_damage_modifier: f32,
        script_name: &'static str,
        disenchant_id: i32,
        food_type: i32,
        min_money_loot: i32,
        max_money_loot: i32,
        duration: i32,
        extra_flags: i32,
    ) -> Self {
        Self {
            entry,
            class,
            subclass,
            sound_override_subclass,
            name,
            displayid,
            quality,
            flags,
            buy_count,
            buy_price,
            sell_price,
            inventory_type,
            allowed_class,
            allowed_race,
            item_level,
            required_level,
            required_skill,
            required_skill_rank,
            required_spell,
            required_honor_rank,
            required_city_rank,
            required_reputation_faction,
            required_reputation_rank,
            max_count,
            stackable,
            container_slots,
            stat_type1,
            stat_value1,
            stat_type2,
            stat_value2,
            stat_type3,
            stat_value3,
            stat_type4,
            stat_value4,
            stat_type5,
            stat_value5,
            stat_type6,
            stat_value6,
            stat_type7,
            stat_value7,
            dmg_min1,
            dmg_max1,
            dmg_type1,
            dmg_min2,
            dmg_max2,
            dmg_type2,
            dmg_min3,
            dmg_max3,
            dmg_type3,
            dmg_min4,
            dmg_max4,
            dmg_type4,
            dmg_min5,
            dmg_max5,
            dmg_type5,
            armor,
            holy_res,
            fire_res,
            nature_res,
            frost_res,
            shadow_res,
            arcane_res,
            delay,
            ammo_type,
            ranged_mod_range,
            spell_id_1,
            spell_trigger_1,
            spell_charges_1,
            spell_ppm_rate_1,
            spell_cooldown_1,
            spell_category_1,
            spell_category_cooldown_1,
            spell_id_2,
            spell_trigger_2,
            spell_charges_2,
            spell_ppm_rate_2,
            spell_cooldown_2,
            spell_category_2,
            spell_category_cooldown_2,
            spell_id_3,
            spell_trigger_3,
            spell_charges_3,
            spell_ppm_rate_3,
            spell_cooldown_3,
            spell_category_3,
            spell_category_cooldown_3,
            spell_id_4,
            spell_trigger_4,
            spell_charges_4,
            spell_ppm_rate_4,
            spell_cooldown_4,
            spell_category_4,
            spell_category_cooldown_4,
            spell_id_5,
            spell_trigger_5,
            spell_charges_5,
            spell_ppm_rate_5,
            spell_cooldown_5,
            spell_category_5,
            spell_category_cooldown_5,
            bonding,
            description,
            page_text,
            language_id,
            page_material,
            start_quest,
            lock_id,
            material,
            sheath,
            random_property,
            random_suffix,
            block,
            itemset,
            max_durability,
            area,
            map,
            bag_family,
            totem_category,
            socket_color_1,
            socket_content_1,
            socket_color_2,
            socket_content_2,
            socket_color_3,
            socket_content_3,
            socket_bonus,
            gem_properties,
            required_disenchant_skill,
            armor_damage_modifier,
            script_name,
            disenchant_id,
            food_type,
            min_money_loot,
            max_money_loot,
            duration,
            extra_flags,
        }
    }

    pub const fn stat_type8(&self) -> i32 {
        0
    }
    pub const fn stat_value8(&self) -> i32 {
        0
    }
    pub const fn stat_type9(&self) -> i32 {
        0
    }
    pub const fn stat_value9(&self) -> i32 {
        0
    }
    pub const fn stat_type10(&self) -> i32 {
        0
    }
    pub const fn stat_value10(&self) -> i32 {
        0
    }
}
